### ISSUE TITLE
DDL part 1: rename table on alter.

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#172]
```sql
alter table dept drop column employees;
```

This should result in new altered table `dept` and an old one named like `db_dept_4_28_2017_19_40_35_576272`.

### Task list:
- [x] Add function to generate table names like `db_dept_4_28_2017_19_40_35_576272`
- [x] Upgrade lock for future historical table we're going to update.
- [x] Change `copy_data_between_tables` to not copy historical rows and update current table.
- [x] Add function which will reset historical read table and set `sys_trx_end=MAX` for all rows with `sys_trx_end=now(6)`.
- [x] Rename an old table to a name like `db_dept_4_28_2017_19_40_35_576272` instead of meaningless tmp name like `#sql-blah-blah.`
- [x] Make it work with INNODB ALTER .. ALGORITHM=COPY too.
- [x] Update/add tests.

**Comment by kevgs** [comment]
## Original ALTER copy operation (exists)

1. Create a table with a new schema and temporary name.
2. Copy data from old no new.
3. Close both tables.
4. Try to rename old to tmp2, then tmp to new.
5. If all succeeded remove an old table with tmp2 name.

## ALTER with versioning (exists)

- Same as above, but we set `sys_trx_{start|end}` are set to the right values during copying data in `copy_data_between_tables()`.
- Similar stuff inside INNODB on `INPLACE ALTER`.

## DDL-based ALTER copy operation (TODO)
1. Rename an old table to a name like `dept_20161223_191443`.
2. Copy only alive rows to a new table.
3. Instead of removing an old table we iterate through its rows and for every alive row set `sys_trx_end = now(6)`.

## Notes
It seems `INPLACE ALTER` is impossible because after operation we should have 2 tables instead of one. And I have no idea how to achieve that from the inside of some storage engine. Thus, we need to disable `INPLACE ALTER` for INNODB.

**Comment by midenok** [comment]
Are all checkboxes done?

**Comment by midenok** [comment]
DDL mode should be controlled by sysvar `versioning_ddl`: OFF(default)/ON.

**Comment by kevgs** [comment]
What is DDL mode? Is it INNODB default `ALTER ALGORITHM`?

**Comment by midenok** [comment]
DDL mode switch (OFF/ON).
