### ISSUE TITLE
0.2 part IV: translations of queries with VTQ

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#20]
- [Dev branch](https://github.com/natsys/mariadb_10.2/tree/am/0.2iv)
- [Commits](https://github.com/natsys/mariadb_10.2/commits/am/0.2iv)
### TODO:
- [x] CONCURR_TRX?
- [x] test VIEW;
- [x] test SHOW;
- [x] test UPDATE of generated;
- [ ] test different transaction types;
- [x] stress test R/W VTQ;
- [ ] check for holes of TRX_ID translation in table;
- [x] test on production build;

**Comment by midenok** [comment]
### Manipulate Query Cache:

`SQL_NO_CACHE`

```
reset query cache;
```

```
set global query_cache_size = 0;
set global query_cache_type = off;
```

**Comment by midenok** [comment]
### Example of fetch with InnoDB SQL:

``` c++
    pars_info_bind_function(pinfo,
                   "fetch_table_stats_step",
                   dict_stats_fetch_table_stats_step,
                   table);
```

``` c++
    ret = que_eval_sql(pinfo,
               "PROCEDURE FETCH_STATS () IS\n"
               "found INT;\n"
               "DECLARE FUNCTION fetch_table_stats_step;\n"
               "DECLARE FUNCTION fetch_index_stats_step;\n"
               "DECLARE CURSOR table_stats_cur IS\n"
               "  SELECT\n"
               /* if you change the selected fields, be
               sure to adjust
               dict_stats_fetch_table_stats_step() */
               "  n_rows,\n"
               "  clustered_index_size,\n"
               "  sum_of_other_index_sizes\n"
               "  FROM \"" TABLE_STATS_NAME "\"\n"
               "  WHERE\n"
               "  database_name = :database_name AND\n"
               "  table_name = :table_name;\n"
               "DECLARE CURSOR index_stats_cur IS\n"
               "  SELECT\n"
               /* if you change the selected fields, be
               sure to adjust
               dict_stats_fetch_index_stats_step() */
               "  index_name,\n"
               "  stat_name,\n"
               "  stat_value,\n"
               "  sample_size\n"
               "  FROM \"" INDEX_STATS_NAME "\"\n"
               "  WHERE\n"
               "  database_name = :database_name AND\n"
               "  table_name = :table_name;\n"

               "BEGIN\n"

               "OPEN table_stats_cur;\n"
               "FETCH table_stats_cur INTO\n"
               "  fetch_table_stats_step();\n"
               "IF (SQL % NOTFOUND) THEN\n"
               "  CLOSE table_stats_cur;\n"
               "  RETURN;\n"
               "END IF;\n"
               "CLOSE table_stats_cur;\n"

               "OPEN index_stats_cur;\n"
               "found := 1;\n"
               "WHILE found = 1 LOOP\n"
               "  FETCH index_stats_cur INTO\n"
               "    fetch_index_stats_step();\n"
               "  IF (SQL % NOTFOUND) THEN\n"
               "    found := 0;\n"
               "  END IF;\n"
               "END LOOP;\n"
               "CLOSE index_stats_cur;\n"

               "END;",
               TRUE, trx);
    /* pinfo is freed by que_eval_sql() */
```

### Initialize, supply parameter

``` c++
    info = pars_info_create();
    pars_info_add_ull_literal(info, "tableid", table_id);

    static const char sql[] =
        "PROCEDURE DROP_INDEXES_PROC () IS\n"
        "ixid CHAR;\n"
        "found INT;\n"

        "DECLARE CURSOR index_cur IS\n"
        " SELECT ID FROM SYS_INDEXES\n"
        " WHERE TABLE_ID=:tableid AND\n"
        " SUBSTR(NAME,0,1)='" TEMP_INDEX_PREFIX_STR "'\n"
        "FOR UPDATE;\n"

        "BEGIN\n"
        "found := 1;\n"
        "OPEN index_cur;\n"
        "WHILE found = 1 LOOP\n"
        "  FETCH index_cur INTO ixid;\n"
        "  IF (SQL % NOTFOUND) THEN\n"
        "    found := 0;\n"
        "  ELSE\n"
        "    DELETE FROM SYS_FIELDS WHERE INDEX_ID=ixid;\n"
        "    DELETE FROM SYS_INDEXES WHERE CURRENT OF index_cur;\n"
        "  END IF;\n"
        "END LOOP;\n"
        "CLOSE index_cur;\n"

        "END;\n";

    error = que_eval_sql(info, sql, FALSE, trx);
```

**Comment by midenok** [comment]
#### NOW() receive value

```
#0  Item_func_now_local::store_now_in_TIME (this=0x7fffd005e120, now_time=0x7fffd005e1e8) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.cc:1718
#1  0x00000000009b8835 in Item_func_now::fix_length_and_dec (this=0x7fffd005e120) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.h:686
#2  0x000000000094c1ee in Item_func::fix_fields (this=0x7fffd005e120, thd=0x7fffd0016070, ref=0x7fffd005e2e8) at /home/midenok/src/mariadb/midenok/src/sql/item_func.cc:236
#3  0x00000000009b23a1 in Item_func_now::fix_fields (this=0x7fffd005e120, thd=0x7fffd0016070, items=0x7fffd005e2e8) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.cc:1708
#4  0x0000000000630274 in setup_fields (thd=0x7fffd0016070, ref_pointer_array=..., fields=..., mark_used_columns=MARK_COLUMNS_READ, sum_func_list=0x7fffd005e6b8, allow_sum_func=0x1) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:7887
#5  0x00000000006cfd50 in JOIN::prepare (this=0x7fffd005e3a8, tables_init=0x0, wild_num=0x0, conds_init=0x0, og_num=0x0, order_init=0x0, skip_order_by=0x0, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffd001a210, unit_arg=0x7fffd0019ac8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:881
#6  0x00000000006d9647 in mysql_select (thd=0x7fffd0016070, tables=0x0, wild_num=0x0, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffd005e388, unit=0x7fffd0019ac8, select_lex=0x7fffd001a210) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3591
#7  0x00000000006ce318 in handle_select (thd=0x7fffd0016070, lex=0x7fffd0019a00, result=0x7fffd005e388, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:377
#8  0x000000000069bd99 in execute_sqlcom_select (thd=0x7fffd0016070, all_tables=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6320
#9  0x0000000000691790 in mysql_execute_command (thd=0x7fffd0016070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3352
#10 0x000000000069f7f3 in mysql_parse (thd=0x7fffd0016070, rawbuf=0x7fffd005e088 "select now(6)", length=0xd, parser_state=0x7ffff7f7cf70, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7792
```

#### NOW() supply value

```
#0  Item_func_now::get_date (this=0x7fffd005e120, res=0x7ffff7f7b3f0, fuzzy_date=0x0) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.cc:1743
#1  0x0000000000909d62 in Item::send (this=0x7fffd005e120, protocol=0x7fffd0016600, buffer=0x7ffff7f7b470) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:6382
#2  0x00000000005d36f1 in Protocol::send_result_set_row (this=0x7fffd0016600, row_items=0x7fffd001a328) at /home/midenok/src/mariadb/midenok/src/sql/protocol.cc:908
#3  0x000000000064f287 in select_send::send_data (this=0x7fffd005e388, items=...) at /home/midenok/src/mariadb/midenok/src/sql/sql_class.cc:2871
#4  0x00000000006d89a2 in JOIN::exec_inner (this=0x7fffd005e3a8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3308
#5  0x00000000006d83bc in JOIN::exec (this=0x7fffd005e3a8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3229
#6  0x00000000006d96f9 in mysql_select (thd=0x7fffd0016070, tables=0x0, wild_num=0x0, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffd005e388, unit=0x7fffd0019ac8, select_lex=0x7fffd001a210) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3613
#7  0x00000000006ce318 in handle_select (thd=0x7fffd0016070, lex=0x7fffd0019a00, result=0x7fffd005e388, setup_tables_done_option=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:377
#8  0x000000000069bd99 in execute_sqlcom_select (thd=0x7fffd0016070, all_tables=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:6320
#9  0x0000000000691790 in mysql_execute_command (thd=0x7fffd0016070) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:3352
#10 0x000000000069f7f3 in mysql_parse (thd=0x7fffd0016070, rawbuf=0x7fffd005e088 "select now(6)", length=0xd, parser_state=0x7ffff7f7cf70, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7792
```

**Comment by midenok** [comment]
``` c++
/*********************************************************************//**
Evaluate the given SQL.
@return error code or DB_SUCCESS */
UNIV_INTERN
dberr_t
que_eval_sql(
/*=========*/
    pars_info_t*    info,   /*!< in: info struct, or NULL */
    const char* sql,    /*!< in: SQL string */
    ibool       reserve_dict_mutex,
                /*!< in: if TRUE, acquire/release
                dict_sys->mutex around call to pars_sql. */
    trx_t*      trx)    /*!< in: trx */
{
    que_thr_t*  thr;
    que_t*      graph;

    ut_a(trx->error_state == DB_SUCCESS);

    if (reserve_dict_mutex) {
        mutex_enter(&dict_sys->mutex);
    }

    graph = pars_sql(info, sql);

    if (reserve_dict_mutex) {
        mutex_exit(&dict_sys->mutex);
    }

    ut_a(graph);

    graph->trx = trx;
    trx->graph = NULL;

    graph->fork_type = QUE_FORK_MYSQL_INTERFACE;

    ut_a(thr = que_fork_start_command(graph));

    que_run_threads(thr);

    if (reserve_dict_mutex) {
        mutex_enter(&dict_sys->mutex);
    }

    que_graph_free(graph);

    if (reserve_dict_mutex) {
        mutex_exit(&dict_sys->mutex);
    }

    return(trx->error_state);
}
```

**Comment by midenok** [comment]
### Info

`trx_t` is created: `trx_create()`, freed: `trx_free()`

**Comment by midenok** [comment]
Read view assigned to trx:

```
#0  trx_assign_read_view (trx=0x7ff244097078) at /home/midenok/src/mariadb/midenok/src/storage/innobase/trx/trx0trx.cc:1531
#1  0x0000000000d2a4a4 in row_sel_step (thr=0x7ff2440fa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0sel.cc:2066
#2  0x0000000000cb972d in que_thr_step (thr=0x7ff2440fa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/que/que0que.cc:1057
#3  0x0000000000cb9a5a in que_run_threads_low (thr=0x7ff2440fa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/que/que0que.cc:1141
#4  0x0000000000cb9bfc in que_run_threads (thr=0x7ff2440fa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/que/que0que.cc:1182
```

**Comment by midenok** [comment]
#### que_thr_step()

``` c++
    } else if (type == QUE_NODE_ASSIGNMENT) {
        assign_step(thr);
    } else if (type == QUE_NODE_SELECT) {
        thr = row_sel_step(thr);
    } else if (type == QUE_NODE_INSERT) {
        thr = row_ins_step(thr);
    } else if (type == QUE_NODE_UPDATE) {
        thr = row_upd_step(thr);
    } else if (type == QUE_NODE_FETCH) {
        thr = fetch_step(thr);
    } else if (type == QUE_NODE_OPEN) {
        thr = open_step(thr);
    } else if (type == QUE_NODE_FUNC) {
```

#### row_sel_step()

``` c++
    if (node->state == SEL_NODE_OPEN) {

        /* It may be that the current session has not yet started
        its transaction, or it has been committed: */

        trx_start_if_not_started_xa(thr_get_trx(thr));

        plan_reset_cursor(sel_node_get_nth_plan(node, 0));

        if (node->consistent_read) {
            /* Assign a read view for the query */
            node->read_view = trx_assign_read_view(
                thr_get_trx(thr));
        } else {
            sym_node_t* table_node;
            enum lock_mode  i_lock_mode;

            if (node->set_x_locks) {
                i_lock_mode = LOCK_IX;
            } else {
                i_lock_mode = LOCK_IS;
            }
```

#### pars_select_statement()

``` C++
    if (for_update) {
        ut_a(!lock_shared);

        select_node->set_x_locks = TRUE;
        select_node->row_lock_mode = LOCK_X;

        select_node->consistent_read = FALSE;
        select_node->read_view = NULL;
    } else if (lock_shared){
        select_node->set_x_locks = FALSE;
        select_node->row_lock_mode = LOCK_S;

        select_node->consistent_read = FALSE;
        select_node->read_view = NULL;
    } else {
        select_node->set_x_locks = FALSE;
        select_node->row_lock_mode = LOCK_S;

        select_node->consistent_read = TRUE;
    }
```

**Comment by midenok** [comment]
Open cursor

```
#0  btr_pcur_open_with_no_init_func (index=0x7fffe06f74f8, tuple=0x7fffcfcf9dd0, mode=0x2, latch_mode=0x1, cursor=0x7fffcfcf9b40, has_search_latch=0x0, file=0x113d3f0 "/home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0sel.cc", line=0x43a, mtr=0x7ffff7f7ae10) at /home/midenok/src/mariadb/midenok/src/storage/innobase/include/btr0pcur.ic:527
#1  0x0000000000d28938 in row_sel_open_pcur (plan=0x7fffcfcf9b30, search_latch_locked=0x0, mtr=0x7ffff7f7ae10) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0sel.cc:1082
#2  0x0000000000d293b3 in row_sel (node=0x7fffcfcf9748, thr=0x7fffcfcfa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0sel.cc:1457
#3  0x0000000000d2a5d2 in row_sel_step (thr=0x7fffcfcfa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/row/row0sel.cc:2118
#4  0x0000000000cb9745 in que_thr_step (thr=0x7fffcfcfa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/que/que0que.cc:1057
#5  0x0000000000cb9a72 in que_run_threads_low (thr=0x7fffcfcfa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/que/que0que.cc:1141
#6  0x0000000000cb9c14 in que_run_threads (thr=0x7fffcfcfa370) at /home/midenok/src/mariadb/midenok/src/storage/innobase/que/que0que.cc:1182
```

**Comment by midenok** [comment]
Wrong stage for `compare_temporal()`:

```
#0  Item_func_vtq_ts::get_date (this=0x7fffcfc5efc0, res=0x7ffff7f7b390, fuzzy_date=0x2000001) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.cc:3296
#1  0x00000000008f8d42 in Item::get_date_with_conversion (this=0x7fffcfc5efc0, ltime=0x7ffff7f7b390, fuzzydate=0x2000001) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:123
#2  0x00000000005d6ab8 in Item::val_datetime_packed (this=0x7fffcfc5efc0) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1272
#3  0x000000000092fbf5 in Item::val_temporal_packed (this=0x7fffcfc5efc0, f_type=MYSQL_TYPE_DATETIME) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1285
#4  0x000000000091d428 in get_datetime_value (thd=0x7fffcfc16070, item_arg=0x7fffcfc5f6e8, cache_arg=0x7fffcfc5f740, f_type=MYSQL_TYPE_DATETIME, is_null=0x7ffff7f7b4a6) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:742
#5  0x000000000091d601 in Arg_comparator::compare_temporal (this=0x7fffcfc5f6e8, type=MYSQL_TYPE_DATETIME) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:788
#6  0x00000000005c9b79 in Arg_comparator::compare_datetime (this=0x7fffcfc5f6e8) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:105
#7  0x00000000009304fc in Arg_comparator::compare (this=0x7fffcfc5f6e8) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:87
#8  0x000000000092058f in Item_func_le::val_int (this=0x7fffcfc5f628) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:1781
#9  0x0000000000929538 in Item_cond::fix_fields (this=0x7fffcfc5f8f8, thd=0x7fffcfc16070, ref=0x7fffcfc5ed70) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:4509
#10 0x000000000063252e in setup_conds (thd=0x7fffcfc16070, tables=0x7fffcfc5e260, leaves=..., conds=0x7fffcfc5ed70) at /home/midenok/src/mariadb/midenok/src/sql/sql_base.cc:8628
#11 0x00000000006cef43 in setup_without_group (thd=0x7fffcfc16070, ref_pointer_array=..., tables=0x7fffcfc5e260, leaves=..., fields=..., all_fields=..., conds=0x7fffcfc5ed70, order=0x0, group=0x0, win_specs=..., win_funcs=..., hidden_group_fields=0x7fffcfc5ec4f, reserved=0x7fffcfc1a4ac) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:642
#12 0x00000000006d02ef in JOIN::prepare (this=0x7fffcfc5e978, tables_init=0x7fffcfc5e260, wild_num=0x1, conds_init=0x0, og_num=0x0, order_init=0x0, skip_order_by=0x0, group_init=0x0, having_init=0x0, proc_param_init=0x0, select_lex_arg=0x7fffcfc1a210, unit_arg=0x7fffcfc19ac8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:908
#13 0x00000000006d9ab3 in mysql_select (thd=0x7fffcfc16070, tables=0x7fffcfc5e260, wild_num=0x1, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffcfc5e958, unit=0x7fffcfc19ac8, select_lex=0x7fffcfc1a210) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3613
```

Correct stage:

```
#0  Item_func_from_unixtime::get_date (this=0x7fffcfc5efc0, ltime=0x7ffff7f7b3c0, fuzzy_date=0x2000001) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.cc:2017
#1  0x00000000008f8d54 in Item::get_date_with_conversion (this=0x7fffcfc5efc0, ltime=0x7ffff7f7b3c0, fuzzydate=0x2000001) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:123
#2  0x00000000005d6ab8 in Item::val_datetime_packed (this=0x7fffcfc5efc0) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1272
#3  0x000000000092fc07 in Item::val_temporal_packed (this=0x7fffcfc5efc0, f_type=MYSQL_TYPE_DATETIME) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1285
#4  0x000000000091d43a in get_datetime_value (thd=0x7fffcfc16070, item_arg=0x7fffcfc5f4d8, cache_arg=0x7fffcfc5f530, f_type=MYSQL_TYPE_DATETIME, is_null=0x7ffff7f7b4d6) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:742
#5  0x000000000091d613 in Arg_comparator::compare_temporal (this=0x7fffcfc5f4d8, type=MYSQL_TYPE_DATETIME) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:788
#6  0x00000000005c9b79 in Arg_comparator::compare_datetime (this=0x7fffcfc5f4d8) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:105
#7  0x000000000093050e in Arg_comparator::compare (this=0x7fffcfc5f4d8) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:87
#8  0x00000000009205a1 in Item_func_le::val_int (this=0x7fffcfc5f418) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:1781
#9  0x00000000008f8be6 in Item::val_bool (this=0x7fffcfc5f418) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:84
#10 0x000000000092a56e in Item_cond_and::val_int (this=0x7fffcfc61bb8) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:4885
#11 0x00000000006fefbe in evaluate_join_record (join=0x7fffcfc5e978, join_tab=0x7fffcfc60ff0, error=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:18457
#12 0x00000000006feb3c in sub_select (join=0x7fffcfc5e978, join_tab=0x7fffcfc60ff0, end_of_records=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:18359
#13 0x00000000006fe065 in do_select (join=0x7fffcfc5e978, procedure=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:17902
#14 0x00000000006d9399 in JOIN::exec_inner (this=0x7fffcfc5e978) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3443
#15 0x00000000006d87aa in JOIN::exec (this=0x7fffcfc5e978) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3255
#16 0x00000000006d9ae7 in mysql_select (thd=0x7fffcfc16070, tables=0x7fffcfc5e260, wild_num=0x1, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffcfc5e958, unit=0x7fffcfc19ac8, select_lex=0x7fffcfc1a210) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3639
```

It is controlled by `const_item_cache` (`const_item()` check)

`const_item_cache` initialized:

``` c++
3668      Used_tables_and_const_cache()
3669       :used_tables_cache(0),
3670        const_item_cache(true)
3671      { }
```

`const_item_cache` updated:

``` c++
3681      void used_tables_and_const_cache_join(const Item *item)
3682      {
3683        used_tables_cache|= item->used_tables();
3684        const_item_cache&= item->const_item();
3685      }
```

**Comment by midenok** [comment]
Another wrong stage:

```
#0  Item_func_vtq_ts::get_date (this=0x7fffcfc5f398, res=0x7ffff7f7b500, fuzzy_date=0x2000001) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.cc:3290
#1  0x00000000008f8e08 in Item::get_date_with_conversion (this=0x7fffcfc5f398, ltime=0x7ffff7f7b500, fuzzydate=0x2000001) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:123
#2  0x00000000005d6ab8 in Item::val_datetime_packed (this=0x7fffcfc5f398) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1272
#3  0x000000000092fcbb in Item::val_temporal_packed (this=0x7fffcfc5f398, f_type=MYSQL_TYPE_DATETIME) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1285
#4  0x000000000091d4ee in get_datetime_value (thd=0x7fffcfc16070, item_arg=0x7fffcfc5f608, cache_arg=0x7fffcfc5f660, f_type=MYSQL_TYPE_DATETIME, is_null=0x7ffff7f7b616) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:742
#5  0x000000000091d6c7 in Arg_comparator::compare_temporal (this=0x7fffcfc5f608, type=MYSQL_TYPE_DATETIME) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:788
#6  0x00000000005c9b79 in Arg_comparator::compare_datetime (this=0x7fffcfc5f608) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:105
#7  0x00000000009305c2 in Arg_comparator::compare (this=0x7fffcfc5f608) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:87
#8  0x00000000009205f5 in Item_func_gt::val_int (this=0x7fffcfc5f548) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:1774
#9  0x000000000094c086 in eval_const_cond (cond=0x7fffcfc5f548) at /home/midenok/src/mariadb/midenok/src/sql/item_func.cc:79
#10 0x00000000006f754a in Item_bool_func2::remove_eq_conds (this=0x7fffcfc5f548, thd=0x7fffcfc16070, cond_value=0x7fffcfc5eda8, top_level_arg=0x1) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:15468
#11 0x00000000006f6339 in optimize_cond (join=0x7fffcfc5eaa8, conds=0x7fffcfc5f548, join_list=0x7fffcfc1a388, ignore_on_conds=0x0, cond_value=0x7fffcfc5eda8, cond_equal=0x7fffcfc5eed0, flags=0x1) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:14999
#12 0x00000000006d1dcf in JOIN::optimize_inner (this=0x7fffcfc5eaa8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1382
#13 0x00000000006d14e6 in JOIN::optimize (this=0x7fffcfc5eaa8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:1187
#14 0x00000000006d9b9b in mysql_select (thd=0x7fffcfc16070, tables=0x7fffcfc5e390, wild_num=0x1, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffcfc5ea88, unit=0x7fffcfc19ac8, select_lex=0x7fffcfc1a210) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3641
```

Correct stage:

```
#0  Item_func_from_unixtime::get_date (this=0x7fffcfc5f640, ltime=0x7ffff7f7b4b0, fuzzy_date=0x2000001) at /home/midenok/src/mariadb/midenok/src/sql/item_timefunc.cc:2017
#1  0x00000000008f8f1e in Item::get_date_with_conversion (this=0x7fffcfc5f640, ltime=0x7ffff7f7b4b0, fuzzydate=0x2000001) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:123
#2  0x00000000005d6ab8 in Item::val_datetime_packed (this=0x7fffcfc5f640) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1272
#3  0x000000000092fdd1 in Item::val_temporal_packed (this=0x7fffcfc5f640, f_type=MYSQL_TYPE_DATETIME) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1285
#4  0x000000000091d604 in get_datetime_value (thd=0x7fffcfc16070, item_arg=0x7fffcfc5f7d0, cache_arg=0x7fffcfc5f828, f_type=MYSQL_TYPE_DATETIME, is_null=0x7ffff7f7b5c6) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:742
#5  0x000000000091d7dd in Arg_comparator::compare_temporal (this=0x7fffcfc5f7d0, type=MYSQL_TYPE_DATETIME) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:788
#6  0x00000000005c9b79 in Arg_comparator::compare_datetime (this=0x7fffcfc5f7d0) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:105
#7  0x00000000009306d8 in Arg_comparator::compare (this=0x7fffcfc5f7d0) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.h:87
#8  0x000000000092070b in Item_func_gt::val_int (this=0x7fffcfc5f710) at /home/midenok/src/mariadb/midenok/src/sql/item_cmpfunc.cc:1774
#9  0x00000000006ff188 in evaluate_join_record (join=0x7fffcfc5eaa8, join_tab=0x7fffcfc60eb0, error=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:18473
#10 0x00000000006feefa in sub_select (join=0x7fffcfc5eaa8, join_tab=0x7fffcfc60eb0, end_of_records=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:18414
#11 0x00000000006fe22f in do_select (join=0x7fffcfc5eaa8, procedure=0x0) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:17918
#12 0x00000000006d9563 in JOIN::exec_inner (this=0x7fffcfc5eaa8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3459
#13 0x00000000006d8974 in JOIN::exec (this=0x7fffcfc5eaa8) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3271
#14 0x00000000006d9cb1 in mysql_select (thd=0x7fffcfc16070, tables=0x7fffcfc5e390, wild_num=0x1, fields=..., conds=0x0, og_num=0x0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=0x80040b00, result=0x7fffcfc5ea88, unit=0x7fffcfc19ac8, select_lex=0x7fffcfc1a210) at /home/midenok/src/mariadb/midenok/src/sql/sql_select.cc:3655
```

```
        //istart= new (thd->mem_root) Item_func_from_unixtime(thd,
        //  new (thd->mem_root) Item_field(thd, fstart));
        //row_end= new (thd->mem_root) Item_func_from_unixtime(thd,
        //  new (thd->mem_root) Item_field(thd, fend));
```

**Comment by midenok** [comment]
``` sql
create table t1(
  x int unsigned,
  y int unsigned,
  sys_start bigint unsigned generated always as row start,
  sys_end bigint unsigned generated always as row end,
  period for system_time (sys_start, sys_end),
  primary key(x, y))
with system versioning
engine innodb;

create table t2(
  x int unsigned,
  y int unsigned,
  sys_start timestamp(6) generated always as row start,
  sys_end timestamp(6) generated always as row end,
  period for system_time (sys_start, sys_end),
  primary key(x, y))
with system versioning
engine myisam;
```

**Comment by midenok** [comment]
### Stress test

``` sql
drop procedure if exists stress;
delimiter ~~
create procedure stress(n varchar(255))
stress_proc:
begin
  set @tabl= concat('s', n);
  set @str= concat('drop table if exists ', @tabl);
  prepare stmt from @str; execute stmt; drop prepare stmt;
  set @str= concat('
    create table ', @tabl, '(
    x int unsigned,
    st bigint unsigned generated always as row start,
    en bigint unsigned generated always as row end,
    period for system_time (st, en))
    with system versioning
    engine innodb');
  prepare stmt from @str; execute stmt; drop prepare stmt;
  set @str= concat('delete from ', @tabl);
  prepare del from @str;
  set @str= concat('insert into ', @tabl, ' (x) values (@i)');
  prepare ins from @str;
  set @str= concat('select x into @x from ', @tabl, ' for system_time as of timestamp @t');
  prepare sel from @str;

  set @i= 0;
  execute ins;
  while true do
    set @t= now(6);
    set @i= @i + 1;
    execute del;
    execute ins;
    execute sel;
    if @x != @i - 1 then
      leave stress_proc;
    end if;
  end while;
end~~
delimiter ;
```
