### ISSUE TITLE
Review tasks

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#303]
From https://github.com/MariaDB/server/pull/478:
- [x] Merge from 10.3 and resolve the conflict in sys_vars.cc
- [x] #307 Fix the Windows build failureIt used to compile, and fail in the bootstrap; now it fails already during compilation.
- [x] #305 Move the VTQ table creation to the upper level and try to revert all changes related to `thr` in InnoDB. When `ha_commit_trans()` takes care of updating the VTQ table, it will be able to return an error. The InnoDB commit cannot return an error.
- [x] Review cleanups part 1
- [x] #302 Ensure that the tests pass, especially --suite=sys_vars.
- [x] #337 Review cleanups part 2
- [x] #307 Fix Windows test failures
- [x] Fix other BuildBot failures

**Comment by midenok** [comment]
After mod_tables patch 70c17c159e0759487024f1f9ab71297b0f184c77 following tests fail:

binlog_encryption.binlog_xa_recover encryption.innodb-bad-key-change
