### ISSUE TITLE
Review cleanups part 2

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#337]
1. Fix or answer comments from [pull request review](https://github.com/MariaDB/server/pull/478#pullrequestreview-78038769).

2. Fix windows warning from [this comment](https://github.com/MariaDB/server/pull/478#issuecomment-345960430):

```
33085349e97a (Aleksey Midenkov     2017-11-10 17:54:46 +0300 8536)   timeval start_time= {thd->start_time, thd->start_time_sec_part};
```
reported as follows:
```
D:\winx64-debug\build\src\sql\table.cc(8536): warning C4838: conversion from 'ulong' to 'long' requires a narrowing conversion [D:\winx64-debug\build\sql\sql.vcxproj]
```
## TODO

- [x] @midenok https://github.com/MariaDB/server/pull/478#discussion_r152241526
- [ ] Not related to AS OF. It more like an idea on MariaDB refactoring https://github.com/MariaDB/server/pull/478#discussion_r152216191
- [x] @midenok change code? https://github.com/MariaDB/server/pull/478#discussion_r152222157
- [x] @midenok https://github.com/MariaDB/server/pull/478#discussion_r152232209
- [x] @midenok https://github.com/MariaDB/server/pull/478#discussion_r152240170
- [x] @midenok is it ok? https://github.com/MariaDB/server/pull/478#discussion_r152242930
- [x] @midenok https://github.com/MariaDB/server/pull/478#discussion_r152247005
- [x] @midenok change code? https://github.com/MariaDB/server/pull/478#discussion_r152252270
- [x] @midenok change code? https://github.com/MariaDB/server/pull/478#discussion_r152252554

**Comment by kevgs** [comment]
```sql
create or replace table t (a int primary key) with system versioning engine innodb;
show create table t;
Table	Create Table
t	CREATE TABLE `t` (
  `a` int(11) NOT NULL,
  `sys_trx_start` bigint(20) unsigned GENERATED ALWAYS AS ROW START,
  `sys_trx_end` bigint(20) unsigned GENERATED ALWAYS AS ROW END NOT NULL,
  PRIMARY KEY (`a`,`sys_trx_end`),
  PERIOD FOR SYSTEM_TIME (`sys_trx_start`, `sys_trx_end`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 WITH SYSTEM VERSIONING
select * from information_schema.innodb_sys_fields where name='sys_trx_end';
INDEX_ID	NAME	POS
27	sys_trx_end	1
create or replace table t (a int) engine innodb;
alter table t add system versioning;
show create table t;
Table	Create Table
t	CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `sys_trx_start` bigint(20) unsigned GENERATED ALWAYS AS ROW START,
  `sys_trx_end` bigint(20) unsigned GENERATED ALWAYS AS ROW END,
  PERIOD FOR SYSTEM_TIME (`sys_trx_start`, `sys_trx_end`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 WITH SYSTEM VERSIONING
select * from information_schema.innodb_sys_fields where name='sys_trx_end';
INDEX_ID	NAME	POS
```
### Additional info
https://github.com/MariaDB/server/pull/478#discussion_r152227626
