### ISSUE TITLE
MDEV-16029 mysqldump: dump and restore historical data

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#505]
### Description
Backup through mysqldump loses historical data from versioned tables.

mysqldump does not read historical rows from the versioned tables, it runs SELECT, not SELECT .. FOR SYSTEM_TIME ALL. But even if we fixed it, it would still be impossible to load this data back, since we are dealing either with invisible columns into which we can't insert at all, or with virtual columns for which values are ignored. So, for now it becomes a known limitation which needs to be documented.

### TODO
- [x] check if table is versioned via `SHOW CREATE`;
- [x] INSERT statements for history;
- [x] test case;
- [x] Test explicit system fields;
- [x] Test modes:
- [x] opt_compact
- [x] path (--tab)
- [x] --no-create-info
- [x] other codeflow branches?
- [x] option to dump with history or current snapshot only;
- [x] Warn about opt_xml;
- [ ] (optionally) dump at specific point in time [MDEV-16355].

### Links
* https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_quote_show_create
* https://mariadb.com/kb/en/library/comment-syntax/
* https://dev.mysql.com/doc/refman/5.5/en/load-xml.html
* https://stackoverflow.com/questions/2934258/how-do-i-get-the-current-time-zone-of-mysql
* https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html
* https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html

**Comment by midenok** [comment]
## Info: mysqldump
* dump_table()
* print_comment()
* fix_for_comment()
* mysql_query_with_error_report()
```c++
3817        print_comment(md_result_file, 0,
3818                      "\n--\n-- Dumping data for table %s\n--\n",
3819                      fix_for_comment(result_table));
3820        
3821        dynstr_append_checked(&query_string, "SELECT /*!40001 SQL_NO_CACHE */ ");
3822        dynstr_append_checked(&query_string, select_field_names.str);
3823        dynstr_append_checked(&query_string, " FROM ");
3824        dynstr_append_checked(&query_string, result_table);
3825
3826        if (where)
3827        {
3828          print_comment(md_result_file, 0, "-- WHERE:  %s\n", fix_for_comment(where));
3829
3830          dynstr_append_checked(&query_string, " WHERE ");
3831          dynstr_append_checked(&query_string, where);
3832        }
....
3848        if (mysql_query_with_error_report(mysql, 0, query_string.str))
3849        {
3850          dynstr_free(&query_string);
3851          DB_error(mysql, "when retrieving data from server");
3852          goto err;
3853        }
3854        if (quick)
3855          res=mysql_use_result(mysql);
3856        else
3857          res=mysql_store_result(mysql);
....
3900        while ((row= mysql_fetch_row(res)))
3901        {
....
4111              fputs(insert_pat.str,md_result_file);
4112              fputs(extended_row.str,md_result_file);
4113              total_length= row_length+init_length;
....
4127        else if (extended_insert && row_break)
4128          fputs(";\n", md_result_file);             /* If not empty table */
4129        fflush(md_result_file);
```
```
(gdb) p query_string.str
$7 = 0xa41b80 "SELECT /*!40001 SQL_NO_CACHE */ `x` FROM `t1`"
(gdb) p select_field_names.str
$8 = 0xa41640 "`x`"
(gdb) p insert_pat.str
$9 = 0xa3ca20 "INSERT INTO `t1` VALUES "
```

**Comment by midenok** [comment]
## Info: server
* dd_frm_type()
* pack_row() (THD::binlog_write_row())
* Log_event::read_log_event()
* Log_event::print_base64()

**Comment by midenok** [comment]
## Bug: `LOAD XML` doesn't fill system fields
### Data: `mysqldump.xml`
```xml
<?xml version="1.0"?>
<mysqldump xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<database name="test">
        <table_structure name="t1">
                <field Field="x" Type="int(11)" Null="YES" Key="" Default="NULL" Extra="" Comment="" />
                <options Name="t1" Engine="MyISAM" Version="10" Row_format="Fixed" Rows="2" Avg_row_length="19" Data_length="38" Max_data_length="5348024557502463" Index_length="1024" Data_free="0" Create_time="2018-07-03 09:30:09" Update_time="2018-07-03 09:30:09" Collation="latin1_swedish_ci" Create_options="" Comment="" Max_index_length="17179868160" Temporary="N" />
        </table_structure>
        <table_data name="t1">
        <row>   
                <field name="x">1</field>
                <field name="row_start">2018-07-03 09:30:09.491532</field>
                <field name="row_end">2018-07-03 09:30:09.491928</field>
        </row>
        <row>   
                <field name="x">2</field>
                <field name="row_start">2018-07-03 09:30:09.491532</field>
                <field name="row_end">2038-01-19 03:14:07.999999</field>
        </row>
        </table_data>
</database>
</mysqldump>
```
### Reproduce
```sql
create or replace table t1 (x int) with system versioning;
load xml infile '../tmp/mysqldump.xml' into table t1;
```
### TODO
- [ ] Add XML option `System_versioning="Y"` for versioned tables.

### Row added
```c++
#0  ha_innobase::write_row (this=0x7fff78043708, record=0x7fff7801e408 "\375\001") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:8018
#1  0x0000000000b1bd34 in handler::ha_write_row (this=0x7fff78043708, buf=0x7fff7801e408 "\375\001") at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:6203
#2  0x000000000076e6d6 in write_record (thd=0x7fff78000d50, table=0x7fff78054890, info=0x7fffe4ece050) at /home/midenok/src/mariadb/trunk/src/sql/sql_insert.cc:2023
#3  0x00000000007a502f in read_xml_field (thd=0x7fff78000d50, info=..., table_list=0x7fff780817c8, fields_vars=..., set_fields=..., set_values=..., read_info=..., row_tag=..., skip_lines=0, ignore_check_option_errors=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_load.cc:1273
#4  0x00000000007a38af in mysql_load (thd=0x7fff78000d50, ex=0x7fff78081740, table_list=0x7fff780817c8, fields_vars=..., set_fields=..., set_values=..., handle_duplicates=DUP_ERROR, ignore=false, read_file_from_client=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_load.cc:648
#5  0x00000000007bc4d6 in mysql_execute_command (thd=0x7fff78000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:5120
#6  0x00000000007b23cf in mysql_parse (thd=0x7fff78000d50, rawbuf=0x7fff78081648 "load xml infile '../tmp/mysqldump.xml' into table t1", length=52, parser_state=0x7fffe4ed1650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8077
```
```c++
5120        res= mysql_load(thd, lex->exchange, first_table, lex->field_list,
5121                        lex->update_list, lex->value_list, lex->duplicates,
5122                        lex->ignore, (bool) lex->local_file);
```
`fields_vars` are either set from `LOAD XML` statement or (if omitted) from table structure:
```c++
  if (!fields_vars.elements)
  {
    Field_iterator_table_ref field_iterator;
    field_iterator.set(table_list);
    for (; !field_iterator.end_of_fields(); field_iterator.next())
    {
      if (field_iterator.field() &&
              field_iterator.field()->invisible > VISIBLE)
        continue;
      Item *item;
      if (!(item= field_iterator.create_item(thd)))
        DBUG_RETURN(TRUE);
      fields_vars.push_back(item->real_item(), thd->mem_root);
    }
```

**Comment by midenok** [comment]
### Field not found error
```sql
load xml infile '../tmp/mysqldump.xml' into table t1 (x, row_start, row_end);
```
```c++
#0  my_error (nr=1054, MyFlags=0) at /home/midenok/src/mariadb/trunk/src/mysys/my_error.c:113
#1  0x0000000000710ae4 in find_field_in_tables (thd=0x7fff78000d50, item=0x7fff78081f80, first_table=0x7fff780817f8, last_table=0x0, ref=0x7fff78082098, report_error=REPORT_ALL_ERRORS, check_privileges=true, register_tree_change=true) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:6235
#2  0x0000000000b3aa7f in Item_field::fix_outer_field (this=0x7fff78081f80, thd=0x7fff78000d50, from_field=0x7fffe4ecd840, reference=0x7fff78082098) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:5972
#3  0x0000000000b3bd61 in Item_field::fix_fields (this=0x7fff78081f80, thd=0x7fff78000d50, reference=0x7fff78082098) at /home/midenok/src/mariadb/trunk/src/sql/item.cc:6226
#4  0x000000000068320a in Item::fix_fields_if_needed (this=0x7fff78081f80, thd=0x7fff78000d50, ref=0x7fff78082098) at /home/midenok/src/mariadb/trunk/src/sql/item.h:822
#5  0x00000000006823d7 in Item::fix_fields_if_needed_for_scalar (this=0x7fff78081f80, thd=0x7fff78000d50, ref=0x7fff78082098) at /home/midenok/src/mariadb/trunk/src/sql/item.h:826
#6  0x0000000000712c68 in setup_fields (thd=0x7fff78000d50, ref_pointer_array=..., fields=..., column_usage=MARK_COLUMNS_WRITE, sum_func_list=0x0, pre_fix=0x0, allow_sum_func=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:7349
#7  0x00000000007a2ad5 in mysql_load (thd=0x7fff78000d50, ex=0x7fff78081770, table_list=0x7fff780817f8, fields_vars=..., set_fields=..., set_values=..., handle_duplicates=DUP_ERROR, ignore=false, read_file_from_client=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_load.cc:462
#8  0x00000000007bc4d6 in mysql_execute_command (thd=0x7fff78000d50) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:5120
#9  0x00000000007b23cf in mysql_parse (thd=0x7fff78000d50, rawbuf=0x7fff78081648 "load xml infile '../tmp/mysqldump.xml' into table t1 (x, row_start, row_end)", length=76, parser_state=0x7fffe4ed1650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8077
```

**Comment by midenok** [comment]
`--xml` option should be supported as well. This imposes following requirements:

1. `--xml` option produces history. System fields contain `Extra="ROW START/END GENERATED"` option. If system fields are system-hidden they are included in `<table_structure>` anyway with `Extra="SYSTEM INVISIBLE ROW START/END GENERATED"` option. `<table_structure>` includes `System_versioning="Y"` option.

Example:

```xml
<?xml version="1.0"?>
<mysqldump xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<database name="test">
        <table_structure name="t1" System_versioning="Y">
                <field Field="x" Type="int(11)" Null="YES" Key="" Default="NULL" Extra="" Comment="" />
                <field Field="row_start" Type="timestamp(6)" Null="NO" Key="" Extra="SYSTEM INVISIBLE ROW START GENERATED" Comment="" />
                <field Field="row_end" Type="timestamp(6)" Null="NO" Key="" Extra="SYSTEM INVISIBLE ROW END GENERATED" Comment="" />
                <options Name="t1" Engine="MyISAM" Version="10" Row_format="Fixed" Rows="2" Avg_row_length="19" Data_length="38" Max_data_length="5348024557502463" Index_length="1024" Data_free="0" Create_time="2018-07-03 09:30:09" Update_time="2018-07-03 09:30:09" Collation="latin1_swedish_ci" Create_options="" Comment="" Max_index_length="17179868160" Temporary="N" />
        </table_structure>
        <table_data name="t1">
        <row>   
                <field name="x">1</field>
                <field name="row_start">2018-07-03 09:30:09.491532</field>
                <field name="row_end">2018-07-03 09:30:09.491928</field>
        </row>
        <row>   
                <field name="x">2</field>
                <field name="row_start">2018-07-03 09:30:09.491532</field>
                <field name="row_end">2038-01-19 03:14:07.999999</field>
        </row>
        </table_data>
</database>
</mysqldump>
```

2. `LOAD XML` loads such data in case `system_versioning_modify_history` is **ON**. When `system_versioning_modify_history` is **OFF** `LOAD XML` fails to set `row_start`, `row_end` fields.

3. `mysqlimport` imports such tables with history.

**Comment by midenok** [comment]
## Timezone bug
`opt_tz_utc` is set by default, but `--compact` doesn't produce `SET time_zone` directives.
### Timezone changed before retrieving data
```c++
#0  connect_to_db (host=0x0, user=0x0, passwd=0x0) at /home/midenok/src/mariadb/trunk/src/client/mysqldump.c:1769
#1  0x0000000000405cf9 in main (argc=2, argv=0x9f4410) at /home/midenok/src/mariadb/trunk/src/client/mysqldump.c:6187
```
```c++
1767      if (opt_tz_utc)
1768      {
1769        my_snprintf(buff, sizeof(buff), "/*!40103 SET TIME_ZONE='+00:00' */");
1770        if (mysql_query_with_error_report(mysql, 0, buff))
1771          DBUG_RETURN(1);
1772      }
```

**Comment by midenok** [comment]
`path` variable is -T (--tab) option. `SET system_versioning_modify_history= ON` is not added in this case. Seems to be no reason to add it to `table.sql` which contains only table structure.

**Comment by midenok** [comment]
## MDEV-16684: mysqldump-no-binlog fails on Windows
### 1. `switch_time_zone()` called
```c++
#0  switch_time_zone (sql_file=0x7ffff67f4720 <_IO_2_1_stdout_>, save_var=0x4b0230 "OLD_TIME_ZONE", delimiter=0x4b0022 ";", time_zone=0x9d4400 <time_zone_str> "+00:00") at /home/midenok/src/mariadb/review/src/client/mysqldump.c:1516
#1  0x000000000040736d in write_header (sql_file=0x7ffff67f4720 <_IO_2_1_stdout_>, db_name=0x7fffffffc56f "test") at /home/midenok/src/mariadb/review/src/client/mysqldump.c:762
#2  0x0000000000405d35 in main (argc=1, argv=0x9f4e08) at /home/midenok/src/mariadb/review/src/client/mysqldump.c:6170
```
### 2. Error printed
```c++
#0  do_show_master_status (mysql_con=0x9d3f00 <mysql_connection>, consistent_binlog_pos=0, have_mariadb_gtid=1, use_gtid=0) at /home/midenok/src/mariadb/review/src/client/mysqldump.c:5269
#1  0x0000000000405f6f in main (argc=1, argv=0x9f4e08) at /home/midenok/src/mariadb/review/src/client/mysqldump.c:6225
```
## Cause
https://jira.mariadb.org/browse/MDEV-16752

**Comment by midenok** [comment]
## Failed tests
### Buildbot
```
main.mysqldump versioning.trx_id main.mysqldump_restore archive.archive_bitfield main.mysql-bug45236 main.openssl_1
```
### Local
```
rpl.rpl_non_direct_mixed_mixing_engines rpl.rpl_row_mixing_engines rpl.rpl_stm_mixing_engines versioning.debug innodb.read_only_recovery innodb.read_only_recover_committed
```
