### ISSUE TITLE
MDEV-16972 Application-time periods support

### ISSUE THREAD

**Issue by FooBarrior** [tempesta-tech/mariadb#532]

**Comment by FooBarrior** [comment]
# Known bugs
## CREATE

- [x]  CREATE ... LIKE craches
- [ ]  CREATE ... LIKE does not promote PERIOD (alter table issue).

- [x]  override timestamp default `ON UPDATE` behavior

# TODO
- [x] check CREATE .. SELECT
- [x] add bitemporal tests
- [ ] add key+period index by default
- [ ] measure db2's FK RI performance on child insert/update (DB2 v12)
- [ ] forbid explicit constraints with period columns (inserts are done without any constraint checks)
