### ISSUE TITLE
MDEV-17520 Instant NOT NULL removal

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#562]
@dr-m:

> I could use some help with MDEV-17520. I fixed the `innodb.instant_alter_null`, and I don’t know about `main.function_defaults_innodb` yet, but I do know that there are a few FIXMEs that should be easy to hit with RQG.

> This code in `instant_alter_column_possible()` should be your starting point:
```
#else // FIXME: Rebuild the affected indexes, not the whole table!
        return ib_table.indexes.count == 1;
```

For ROW_FORMAT=COMPACT or DYNAMIC, we do have to rebuild secondary indexes that depend on the affected columns. For ROW_FORMAT=REDUNDANT, nothing will have to be done, because the secondary index records already contain the "is null" flags.

All secondary indexes whose `index->fields[i].col` points to an affected column must be dropped and added, that is, they must be added to `ha_innobase_inplace_ctx::drop_index`, `ha_innobase_inplace_ctx::add_index`, and `ha_innobase_inplace_ctx::add_key_numbers`. Because `ctx` does not exist in `ha_innobase::check_if_supported_inplace_alter()` yet, some code duplication is unavoidable. Due to the index add/drop, `ha_innobase::check_if_supported_inplace_alter()` must not return `HA_ALTER_INPLACE_INSTANT`; the best that it can return is `HA_ALTER_INPLACE_NOCOPY_NO_LOCK`, that is, allow ALGORITHM=NOCOPY but not ALGORITHM=INSTANT.

There is a predicate `dict_index_contains_col_or_prefix()` that I’d move to an inline member function of `dict_index_t`.

**Comment by midenok** [comment]
### 1. `instant_alter_column_possible()` 
```c++
#0  instant_alter_column_possible (ib_table=..., ha_alter_info=0x7ffff41e8848, table=0x7fff84082d38) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:1527
#1  0x0000000000dd3297 in ha_innobase::check_if_supported_inplace_alter (this=0x7fff840804d0, altered_table=0x7fff84085ff8, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:1841
#2  0x00000000008c29c1 in mysql_alter_table (thd=0x7fff84000cf8, new_db=0x7fff840053b0, new_name=0x7fff84005780, create_info=0x7ffff41ea370, table_list=0x7fff84014f88, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9666
#3  0x0000000000969c5f in Sql_cmd_alter_table::execute (this=0x7fff840156e8, thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#4  0x00000000007cd454 in mysql_execute_command (thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#5  0x00000000007bf010 in mysql_parse (thd=0x7fff84000cf8, rawbuf=0x7fff84014e80 "alter table t1 modify y int, algorithm=nocopy", length=45, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```
### 2. `ha_innobase_inplace_ctx` constructed
```c++
#0  ha_innobase_inplace_ctx::ha_innobase_inplace_ctx (this=0x7fff840167c0, prebuilt_arg=@0x7fff84080ba0: 0x7fff84083968, drop_arg=0x0, num_to_drop_arg=0, rename_arg=0x0, num_to_rename_arg=0, drop_fk_arg=0x0, num_to_drop_fk_arg=0, add_fk_arg=0x0, num_to_add_fk_arg=0, online_arg=true, heap_arg=0x7fff840876d0, new_table_arg=0x7fff84021e88, col_names_arg=0x0, add_autoinc_arg=18446744073709551615, autoinc_col_min_value_arg=0, autoinc_col_max_value_arg=0, allow_not_null_flag=false, page_compressed=false, page_compression_level_arg=0) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:999
#1  0x0000000000dda2e8 in ha_innobase::prepare_inplace_alter_table (this=0x7fff840804d0, altered_table=0x7fff84085ff8, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:7932
#2  0x0000000000b2d06e in handler::ha_prepare_inplace_alter_table (this=0x7fff840804d0, altered_table=0x7fff84085ff8, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:4437
#3  0x00000000008c9585 in mysql_inplace_alter_table (thd=0x7fff84000cf8, table_list=0x7fff84014f88, table=0x7fff84082d38, altered_table=0x7fff84085ff8, ha_alter_info=0x7ffff41e8848, inplace_supported=HA_ALTER_INPLACE_NOCOPY_NO_LOCK, target_mdl_request=0x7ffff41e8ee8, alter_ctx=0x7ffff41e9098) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:7516
#4  0x00000000008c2b37 in mysql_alter_table (thd=0x7fff84000cf8, new_db=0x7fff840053b0, new_name=0x7fff84005780, create_info=0x7ffff41ea370, table_list=0x7fff84014f88, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9691
#5  0x0000000000969c5f in Sql_cmd_alter_table::execute (this=0x7fff840156e8, thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#6  0x00000000007cd454 in mysql_execute_command (thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#7  0x00000000007bf010 in mysql_parse (thd=0x7fff84000cf8, rawbuf=0x7fff84014e80 "alter table t1 modify y int, algorithm=nocopy", length=45, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```
### 3. index added
```c++
#0  row_merge_rename_index_to_add (trx=0x7fffe8187300, table_id=55, index_id=70) at /home/midenok/src/mariadb/marko/src/storage/innobase/row/row0merge.cc:4206
#1  0x0000000000dfff4e in commit_try_norebuild (ha_alter_info=0x7ffff41e8848, ctx=0x7fff840167e0, altered_table=0x7fff84097198, old_table=0x7fff84089c18, trx=0x7fffe8187300, table_name=0x7fff84092e35 "t1") at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:10060
#2  0x0000000000de72b0 in ha_innobase::commit_inplace_alter_table (this=0x7fff840914b0, altered_table=0x7fff84097198, ha_alter_info=0x7ffff41e8848, commit=true) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:10784
#3  0x0000000000b2d1ba in handler::ha_commit_inplace_alter_table (this=0x7fff840914b0, altered_table=0x7fff84097198, ha_alter_info=0x7ffff41e8848, commit=true) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:4457
#4  0x00000000008c9a9b in mysql_inplace_alter_table (thd=0x7fff84000cf8, table_list=0x7fff84014f88, table=0x7fff84089c18, altered_table=0x7fff84097198, ha_alter_info=0x7ffff41e8848, inplace_supported=HA_ALTER_INPLACE_NOCOPY_NO_LOCK, target_mdl_request=0x7ffff41e8ee8, alter_ctx=0x7ffff41e9098) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:7599
#5  0x00000000008c2b37 in mysql_alter_table (thd=0x7fff84000cf8, new_db=0x7fff840053b0, new_name=0x7fff84005780, create_info=0x7ffff41ea370, table_list=0x7fff84014f88, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9691
#6  0x0000000000969c5f in Sql_cmd_alter_table::execute (this=0x7fff840156b8, thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#7  0x00000000007cd454 in mysql_execute_command (thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#8  0x00000000007bf010 in mysql_parse (thd=0x7fff84000cf8, rawbuf=0x7fff84014e80 "alter table t1 add index (z), drop index y", length=42, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```
### 4. index dropped
```c++
#0  row_merge_rename_index_to_drop (trx=0x7fffe8187300, table_id=54, index_id=66) at /home/midenok/src/mariadb/marko/src/storage/innobase/row/row0merge.cc:4258
#1  0x0000000000e0027e in commit_try_norebuild (ha_alter_info=0x7ffff41e8848, ctx=0x7fff840167e0, altered_table=0x7fff84092258, old_table=0x7fff8408f298, trx=0x7fffe8187300, table_name=0x7fff84090ed5 "t1") at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:10094
#2  0x0000000000de72b0 in ha_innobase::commit_inplace_alter_table (this=0x7fff84088c10, altered_table=0x7fff84092258, ha_alter_info=0x7ffff41e8848, commit=true) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:10784
#3  0x0000000000b2d1ba in handler::ha_commit_inplace_alter_table (this=0x7fff84088c10, altered_table=0x7fff84092258, ha_alter_info=0x7ffff41e8848, commit=true) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:4457
#4  0x00000000008c9a9b in mysql_inplace_alter_table (thd=0x7fff84000cf8, table_list=0x7fff84014f88, table=0x7fff8408f298, altered_table=0x7fff84092258, ha_alter_info=0x7ffff41e8848, inplace_supported=HA_ALTER_INPLACE_NOCOPY_NO_LOCK, target_mdl_request=0x7ffff41e8ee8, alter_ctx=0x7ffff41e9098) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:7599
#5  0x00000000008c2b37 in mysql_alter_table (thd=0x7fff84000cf8, new_db=0x7fff840053b0, new_name=0x7fff84005780, create_info=0x7ffff41ea370, table_list=0x7fff84014f88, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9691
#6  0x0000000000969c5f in Sql_cmd_alter_table::execute (this=0x7fff840156b8, thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#7  0x00000000007cd454 in mysql_execute_command (thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#8  0x00000000007bf010 in mysql_parse (thd=0x7fff84000cf8, rawbuf=0x7fff84014e80 "alter table t1 add index (z), drop index y", length=42, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```

**Comment by midenok** [comment]
## Info: add index
### 1. `ha_innobase_inplace_ctx` constructed
```c++
#0  ha_innobase_inplace_ctx::ha_innobase_inplace_ctx (this=0x7fff7c0168c8, prebuilt_arg=@0x7fff7c07a9f0: 0x7fff7c07f268, drop_arg=0x0, num_to_drop_arg=0, rename_arg=0x0, num_to_rename_arg=0, drop_fk_arg=0x0, num_to_drop_fk_arg=0, add_fk_arg=0x0, num_to_add_fk_arg=0, online_arg=true, heap_arg=0x7fff7c08aa60, new_table_arg=0x7fff7c021e88, col_names_arg=0x0, add_autoinc_arg=18446744073709551615, autoinc_col_min_value_arg=0, autoinc_col_max_value_arg=0, allow_not_null_flag=false, page_compressed=false, page_compression_level_arg=0) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:999
#1  0x0000000000ddae4b in ha_innobase::prepare_inplace_alter_table (this=0x7fff7c07a320, altered_table=0x7fff7c089388, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:8098
#2  0x0000000000b2cfde in handler::ha_prepare_inplace_alter_table (this=0x7fff7c07a320, altered_table=0x7fff7c089388, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:4437
#3  0x00000000008c94f5 in mysql_inplace_alter_table (thd=0x7fff7c000cf8, table_list=0x7fff7c014f68, table=0x7fff7c07e638, altered_table=0x7fff7c089388, ha_alter_info=0x7ffff41e8848, inplace_supported=HA_ALTER_INPLACE_NOCOPY_NO_LOCK, target_mdl_request=0x7ffff41e8ee8, alter_ctx=0x7ffff41e9098) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:7516
#4  0x00000000008c2aa7 in mysql_alter_table (thd=0x7fff7c000cf8, new_db=0x7fff7c0053b0, new_name=0x7fff7c005780, create_info=0x7ffff41ea370, table_list=0x7fff7c014f68, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9691
#5  0x0000000000969bcf in Sql_cmd_alter_table::execute (this=0x7fff7c015670, thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#6  0x00000000007cd3c4 in mysql_execute_command (thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#7  0x00000000007bef80 in mysql_parse (thd=0x7fff7c000cf8, rawbuf=0x7fff7c014e80 "alter table t1 add index (z)", length=28, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```
### 2. `ctx->add_index` increased
```c++
#0  prepare_inplace_alter_table_dict (ha_alter_info=0x7ffff41e8848, altered_table=0x7fff7c089388, old_table=0x7fff7c07e638, table_name=0x7fff7c084fe5 "t1", flags=33, flags2=80, fts_doc_id_col=18446744073709551615, add_fts_doc_id=false, add_fts_doc_id_idx=false) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:6427
#1  0x0000000000ddaf3f in ha_innobase::prepare_inplace_alter_table (this=0x7fff7c07a320, altered_table=0x7fff7c089388, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:8111
#2  0x0000000000b2cfde in handler::ha_prepare_inplace_alter_table (this=0x7fff7c07a320, altered_table=0x7fff7c089388, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:4437
#3  0x00000000008c94f5 in mysql_inplace_alter_table (thd=0x7fff7c000cf8, table_list=0x7fff7c014f68, table=0x7fff7c07e638, altered_table=0x7fff7c089388, ha_alter_info=0x7ffff41e8848, inplace_supported=HA_ALTER_INPLACE_NOCOPY_NO_LOCK, target_mdl_request=0x7ffff41e8ee8, alter_ctx=0x7ffff41e9098) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:7516
#4  0x00000000008c2aa7 in mysql_alter_table (thd=0x7fff7c000cf8, new_db=0x7fff7c0053b0, new_name=0x7fff7c005780, create_info=0x7ffff41ea370, table_list=0x7fff7c014f68, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9691
#5  0x0000000000969bcf in Sql_cmd_alter_table::execute (this=0x7fff7c015670, thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#6  0x00000000007cd3c4 in mysql_execute_command (thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#7  0x00000000007bef80 in mysql_parse (thd=0x7fff7c000cf8, rawbuf=0x7fff7c014e80 "alter table t1 add index (z)", length=28, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```
```c++
6418            /* Create the index metadata. */
6419            for (ulint a = 0; a < ctx->num_to_add_index; a++) {
6420                    if (index_defs[a].ind_type & DICT_VIRTUAL
6421                        && ctx->num_to_drop_vcol > 0 && !new_clustered) {
6422                            innodb_v_adjust_idx_col(ha_alter_info, old_table,
6423                                                    ctx->num_to_drop_vcol,
6424                                                    &index_defs[a]);
6425                    }
6426
6427                    ctx->add_index[a] = row_merge_create_index(
6428                            ctx->new_table, &index_defs[a], add_v);
6429
6430                    add_key_nums[a] = index_defs[a].key_number;
6431
6432                    DBUG_ASSERT(ctx->add_index[a]->is_committed()
6433                                == !!new_clustered);
6434            }
```
## Info: drop index
### 1. `ha_innobase_inplace_ctx` constructed
```c++
#0  ha_innobase_inplace_ctx::ha_innobase_inplace_ctx (this=0x7fff7c0166f8, prebuilt_arg=@0x7fff7c081140: 0x7fff7c07f268, drop_arg=0x7fff7c08cdc8, num_to_drop_arg=1, rename_arg=0x0, num_to_rename_arg=0, drop_fk_arg=0x0, num_to_drop_fk_arg=0, add_fk_arg=0x0, num_to_add_fk_arg=0, online_arg=true, heap_arg=0x7fff7c08cd40, new_table_arg=0x7fff7c021e88, col_names_arg=0x0, add_autoinc_arg=18446744073709551615, autoinc_col_min_value_arg=0, autoinc_col_max_value_arg=0, allow_not_null_flag=false, page_compressed=false, page_compression_level_arg=0) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:999
#1  0x0000000000dda138 in ha_innobase::prepare_inplace_alter_table (this=0x7fff7c080a70, altered_table=0x7fff7c08c198, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:7964
#2  0x0000000000b2cfde in handler::ha_prepare_inplace_alter_table (this=0x7fff7c080a70, altered_table=0x7fff7c08c198, ha_alter_info=0x7ffff41e8848) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:4437
#3  0x00000000008c94f5 in mysql_inplace_alter_table (thd=0x7fff7c000cf8, table_list=0x7fff7c014f68, table=0x7fff7c07e638, altered_table=0x7fff7c08c198, ha_alter_info=0x7ffff41e8848, inplace_supported=HA_ALTER_INPLACE_INSTANT, target_mdl_request=0x7ffff41e8ee8, alter_ctx=0x7ffff41e9098) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:7516
#4  0x00000000008c2aa7 in mysql_alter_table (thd=0x7fff7c000cf8, new_db=0x7fff7c0053b0, new_name=0x7fff7c005780, create_info=0x7ffff41ea370, table_list=0x7fff7c014f68, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9691
#5  0x0000000000969bcf in Sql_cmd_alter_table::execute (this=0x7fff7c0155d0, thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#6  0x00000000007cd3c4 in mysql_execute_command (thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#7  0x00000000007bef80 in mysql_parse (thd=0x7fff7c000cf8, rawbuf=0x7fff7c014e80 "alter table t1 drop index z", length=27, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```
`drop_index` is initialized in constructor.

**Comment by midenok** [comment]
### TODO
- [x] handle case when affected index is dropped in same ALTER
```c++
		for (uint i = 0; i < ha_alter_info->index_drop_count; i++) {
			const KEY*	key
				= ha_alter_info->index_drop_buffer[i];
			dict_index_t*	index
				= dict_table_get_index_on_name(
					indexed_table, key->name.str);

			if (!index) {
				push_warning_printf(
					m_user_thd,
					Sql_condition::WARN_LEVEL_WARN,
					HA_ERR_WRONG_INDEX,
					"InnoDB could not find key"
					" with name %s", key->name);
			} else {
				ut_ad(!index->to_be_dropped);
				if (!index->is_primary()) {
					drop_index[n_drop_index++] = index;
				} else {
					drop_primary = index;
				}
			}
		}
```

### Idea 1
Put key names from `index_drop_buffer` into `std::set` and then check index names against it. Maybe put index names into another `std::set` and use `std::includes`.
#### Problem
Key names list is expected not much, so allocator algorithm can take more time than `std::set` search wins. Number of items is known: allocator should preallocate all needed memory first, but this is not implemented for `std::set`. Allocator should not allocate from heap: best option is conditionally allocate from stack or from `mem_heap_t` based on given number of elements (stack for not many, `mem_heap_t` for many).
### Idea 2
Make iterator over affected indexes and iterator over `index_drop_buffer`, then use linear search algorithms.
#### Problem
Usage of `dict_table_get_index_on_name()` is not justified in each iteration over `index_drop_buffer`.
### Idea 3 (current solution)
Make iterator over affected indexes then check that **none** of their names is `index_drop_buffer` names.

**Comment by midenok** [comment]
- [ ] do I have to set `to_be_dropped` ?

**Comment by midenok** [comment]
### `innobase_create_key_defs()` assertion
```c++
#3  0x00007ffff6d15142 in __GI___assert_fail (assertion=0x1666a54 "indexdef > indexdefs", file=0x16637e0 "/home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc", line=3927, function=0x166681c "index_def_t *innobase_create_key_defs(mem_heap_t *, const Alter_inplace_info *, const TABLE *, ulint &, ulint &, bool, ulint &, bool &, bool &, const TABLE *)") at assert.c:101
#4  0x0000000000dee542 in innobase_create_key_defs (heap=0x7fff84086690, ha_alter_info=0x7ffff41e8840, altered_table=0x7fff84084bc8, n_add=@0x7fff84016d38: 0, n_fts_add=@0x7ffff41e6898: 0, got_default_clust=true, fts_doc_id_col=@0x7ffff41e6920: 18446744073709551615, add_fts_doc_id=@0x7ffff41e68cf: false, add_fts_doc_idx=@0x7ffff41e68ce: false, table=0x7fff8407fa68) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:3927
#5  0x0000000000dde7c3 in prepare_inplace_alter_table_dict (ha_alter_info=0x7ffff41e8840, altered_table=0x7fff84084bc8, old_table=0x7fff8407fa68, table_name=0x7fff84033995 "t1", flags=33, flags2=80, fts_doc_id_col=18446744073709551615, add_fts_doc_id=false, add_fts_doc_id_idx=false) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:6177
#6  0x0000000000ddaf8f in ha_innobase::prepare_inplace_alter_table (this=0x7fff84080630, altered_table=0x7fff84084bc8, ha_alter_info=0x7ffff41e8840) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:8225
#7  0x0000000000b2cfee in handler::ha_prepare_inplace_alter_table (this=0x7fff84080630, altered_table=0x7fff84084bc8, ha_alter_info=0x7ffff41e8840) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:4437
#8  0x00000000008c94f5 in mysql_inplace_alter_table (thd=0x7fff84000cf8, table_list=0x7fff84014f68, table=0x7fff8407fa68, altered_table=0x7fff84084bc8, ha_alter_info=0x7ffff41e8840, inplace_supported=HA_ALTER_INPLACE_NOCOPY_NO_LOCK, target_mdl_request=0x7ffff41e8ee8, alter_ctx=0x7ffff41e9098) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:7516
#9  0x00000000008c2aa7 in mysql_alter_table (thd=0x7fff84000cf8, new_db=0x7fff840053b0, new_name=0x7fff84005780, create_info=0x7ffff41ea370, table_list=0x7fff84014f68, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9691
#10 0x0000000000969bdf in Sql_cmd_alter_table::execute (this=0x7fff840156c0, thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#11 0x00000000007cd3c4 in mysql_execute_command (thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#12 0x00000000007bef80 in mysql_parse (thd=0x7fff84000cf8, rawbuf=0x7fff84014e80 "alter table t1 modify b int", length=27, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```
#### frame 4
```
3927            DBUG_ASSERT(indexdef > indexdefs);
(gdb) p indexdef
$1 = (index_def_t *) 0x7fff840868a0
(gdb) p indexdefs
$2 = (index_def_t *) 0x7fff840868a0
```
### Cause
`ALTER_ADD_NON_UNIQUE_NON_PRIM_INDEX` added, but `index_add_buffer` is empty.

### TODO
- [x] test rebuilding of FTS indexes, see
```c++
			if (indexdef->ind_type & DICT_FTS) {
				n_fts_add++;
			}
```
- [x] test that all indexes are rebuilt including complex ones (`abc`).

FTS indexes are not supported:
```
mysqltest: At line 18: query 'alter table t1 modify a varchar(300), algorithm=inplace' failed: 1846: ALGORITHM=INPLACE is not supported. Reason: InnoDB presently supports one FULLTEXT index creation at a time. Try ALGORITHM=COPY
```

It is impossible to check which indexes was rebuilt, because `INDEX_ID` changes for all indexes (since `ALTER_COLUMN_NULLABLE` is in `INNOBASE_ALTER_REBUILD` (and then it is added to `avoid_rebuild`)). @dr-m:
> it should not change any more. See MDEV-17793. I tried to work around a bug by reassigning table_id, but that caused "drop table" on rollback.

**Comment by midenok** [comment]
## Bug 1: FK failure
### Reproduce
```sql
drop table t2;
create or replace table t1 (a int not null, index (a));
create or replace table t2 (b int, foreign key (b) references t1(a));
alter table t1 change a id int;
```
### Result
```
ERROR 1553 (HY000): Cannot drop index 'a': needed in a foreign key constraint
```
```c++
#0  my_error (nr=1553, MyFlags=0) at /home/midenok/src/mariadb/marko/src/mysys/my_error.c:113
#1  0x0000000000b2b059 in handler::print_error (this=0x7fff840a4090, error=162, errflag=0) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:3804
#2  0x0000000000ddb6ac in ha_innobase::prepare_inplace_alter_table (this=0x7fff840a4090, altered_table=0x7fff840a7798, ha_alter_info=0x7ffff41e8840) at /home/midenok/src/mariadb/marko/src/storage/innobase/handler/handler0alter.cc:7999
#3  0x0000000000b2d07e in handler::ha_prepare_inplace_alter_table (this=0x7fff840a4090, altered_table=0x7fff840a7798, ha_alter_info=0x7ffff41e8840) at /home/midenok/src/mariadb/marko/src/sql/handler.cc:4437
#4  0x00000000008c9585 in mysql_inplace_alter_table (thd=0x7fff84000cf8, table_list=0x7fff84014f68, table=0x7fff840a34c8, altered_table=0x7fff840a7798, ha_alter_info=0x7ffff41e8840, inplace_supported=HA_ALTER_INPLACE_NOCOPY_NO_LOCK, target_mdl_request=0x7ffff41e8ee8, alter_ctx=0x7ffff41e9098) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:7516
#5  0x00000000008c2b37 in mysql_alter_table (thd=0x7fff84000cf8, new_db=0x7fff840053b0, new_name=0x7fff84005780, create_info=0x7ffff41ea370, table_list=0x7fff84014f68, alter_info=0x7ffff41ea2b8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/marko/src/sql/sql_table.cc:9691
#6  0x0000000000969c6f in Sql_cmd_alter_table::execute (this=0x7fff840156c8, thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_alter.cc:491
#7  0x00000000007cd454 in mysql_execute_command (thd=0x7fff84000cf8) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:6290
#8  0x00000000007bf010 in mysql_parse (thd=0x7fff84000cf8, rawbuf=0x7fff84014e80 "alter table t1 change a id int", length=30, parser_state=0x7ffff41ed640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/marko/src/sql/sql_parse.cc:8092
```
```c++
7991                    if (m_prebuilt->trx->check_foreigns) {
7992                            for (uint i = 0; i < n_drop_index; i++) {
7993                                    dict_index_t*   index = drop_index[i];
7994
7995                                    if (innobase_check_foreign_key_index(
7996                                                    ha_alter_info, index,
7997                                                    indexed_table, col_names,
7998                                                    m_prebuilt->trx, drop_fk, n_drop_fk)) {
7999                                            row_mysql_unlock_data_dictionary(
8000                                                    m_prebuilt->trx);
8001                                            m_prebuilt->trx->error_info = index;
8002                                            print_error(HA_ERR_DROP_INDEX_FK,
8003                                                    MYF(0));
8004                                            goto err_exit;
8005                                    }
8006                            }
```
### Tests affected
```
innodb.foreign_key innodb.innodb-alter
```

**Comment by midenok** [comment]
Sometimes COPY is not possible while INPLACE is possible:
```sql
drop table t2;
create or replace table t1
(a int not null,
 b int not null,
 index idx(a)) engine=innodb;

create or replace table t2
(a int key,
 b int,
 index ind(b),
 foreign key (b) references t1(a) on delete cascade on update cascade)
 engine=innodb;

alter table t1 change a id int, algorithm copy;
```
```
ERROR 1846 (0A000): ALGORITHM=COPY is not supported. Reason: Columns participating in a foreign key are renamed. Try ALGORITHM=INPLACE
```

COPY is not supported for FK-involved indexes, rebuild is not possible because unable to DROP FK-involved index.

**Comment by midenok** [comment]
### Fix
```diff
--- a/storage/innobase/handler/handler0alter.cc
+++ b/storage/innobase/handler/handler0alter.cc
@@ -7992,7 +7992,8 @@ ha_innobase::prepare_inplace_alter_table(
                        for (uint i = 0; i < n_drop_index; i++) {
                                dict_index_t*   index = drop_index[i];
 
-                               if (innobase_check_foreign_key_index(
+                               if (!index->to_be_rebuilt
+                                   && innobase_check_foreign_key_index(
                                                ha_alter_info, index,
                                                indexed_table, col_names,
                                                m_prebuilt->trx, drop_fk, n_drop_fk)) {
```

**Comment by midenok** [comment]
https://github.com/MariaDB/server/pull/1019
