### ISSUE TITLE
MDEV-17553 Enable setting start datetime for interval partitioned history of system versioned tables

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#574]
### TODO
- [x] SHOW CREATE;
- [x] Calculate STARTS boundary depending on INTERVAL;
- [x] Warn about first partition is longer than INTERVAL when STARTS timestamp is in further future;
- [x] test cases for different timezones and STARTS timestamp in past, in future;
- [x] test STARTS wrong, zero-filled timestamps;
- [x] test STARTS as DATETIME and as epoch time in seconds;
- [x] test rotation.

### Partition full warning
```c++
#0  my_error (nr=4114, MyFlags=2112) at /home/midenok/src/mariadb/trunk/src/mysys/my_error.c:113
#1  0x0000000000958fdf in partition_info::vers_set_hist_part (this=0x7fff800954e0, thd=0x7fff80015038) at /home/midenok/src/mariadb/trunk/src/sql/partition_info.cc:880
#2  0x000000000140295d in ha_partition::external_lock (this=0x7fff80094c90, thd=0x7fff80015038, lock_type=1) at /home/midenok/src/mariadb/trunk/src/sql/ha_partition.cc:3954
#3  0x0000000000b451a4 in handler::ha_external_lock (this=0x7fff80094c90, thd=0x7fff80015038, lock_type=1) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:6171
#4  0x0000000000c9e381 in lock_external (thd=0x7fff80015038, tables=0x7fff80086590, count=1) at /home/midenok/src/mariadb/trunk/src/sql/lock.cc:396
#5  0x0000000000c9dee3 in mysql_lock_tables (thd=0x7fff80015038, sql_lock=0x7fff80086570, flags=0) at /home/midenok/src/mariadb/trunk/src/sql/lock.cc:341
#6  0x0000000000c9d0f2 in mysql_lock_tables (thd=0x7fff80015038, tables=0x7fff80086568, count=1, flags=0) at /home/midenok/src/mariadb/trunk/src/sql/lock.cc:304
#7  0x000000000072ee77 in lock_tables (thd=0x7fff80015038, tables=0x7fff80085968, count=1, flags=0) at /home/midenok/src/mariadb/trunk/src/sql/sql_base.cc:5262
#8  0x0000000000904c61 in mysql_update (thd=0x7fff80015038, table_list=0x7fff80085968, fields=..., values=..., conds=0x0, order_num=0, order=0x0, limit=18446744073709551615, handle_duplicates=DUP_ERROR, ignore=false, found_return=0x7ffff7ea1e88, updated_return=0x7ffff7ea1e80) at /home/midenok/src/mariadb/trunk/src/sql/sql_update.cc:374
#9  0x00000000007e01c9 in mysql_execute_command (thd=0x7fff80015038) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:4576
#10 0x00000000007d839f in mysql_parse (thd=0x7fff80015038, rawbuf=0x7fff80085890 "update t1 set i= i + 1", length=22, parser_state=0x7ffff7ea3650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8087
```
### Record is moved to new partition
```c++
#7  0x0000000000b45b1a in handler::ha_write_row (this=0x7fff80087b78, buf=0x7fff80084d58 "\375\002") at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:6256
#8  0x00000000013fc944 in ha_partition::copy_partitions (this=0x7fff800940e0, copied=0x7ffff7e9d580, deleted=0x7ffff7e9d588) at /home/midenok/src/mariadb/trunk/src/sql/ha_partition.cc:2117
#9  0x00000000013fc550 in ha_partition::change_partitions (this=0x7fff800940e0, create_info=0x7ffff7ea0208, path=0x7ffff7e9d060 "./test/t1", copied=0x7ffff7e9d580, deleted=0x7ffff7e9d588, pack_frm_data=0x0, pack_frm_len=0) at /home/midenok/src/mariadb/trunk/src/sql/ha_partition.cc:2029
#10 0x0000000000b40bc9 in handler::ha_change_partitions (this=0x7fff800940e0, create_info=0x7ffff7ea0208, path=0x7ffff7e9d060 "./test/t1", copied=0x7ffff7e9d580, deleted=0x7ffff7e9d588, pack_frm_data=0x0, pack_frm_len=0) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:4651
#11 0x0000000000d4a01b in mysql_change_partitions (lpt=0x7ffff7e9d578) at /home/midenok/src/mariadb/trunk/src/sql/sql_partition.cc:5996
#12 0x0000000000d4938d in fast_alter_partition_table (thd=0x7fff80015038, table=0x7fff800e2ad8, alter_info=0x7ffff7ea0138, create_info=0x7ffff7ea0208, table_list=0x7fff800859a8, db=0x7ffff7e9ee88, table_name=0x7ffff7e9ee98) at /home/midenok/src/mariadb/trunk/src/sql/sql_partition.cc:7361
#13 0x00000000008dd9bd in mysql_alter_table (thd=0x7fff80015038, new_db=0x7fff80019778, new_name=0x7fff80019b48, create_info=0x7ffff7ea0208, table_list=0x7fff800859a8, alter_info=0x7ffff7ea0138, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9551
#14 0x0000000000985dff in Sql_cmd_alter_table::execute (this=0x7fff80086428, thd=0x7fff80015038) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:491
#15 0x00000000007e6633 in mysql_execute_command (thd=0x7fff80015038) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6288
#16 0x00000000007d839f in mysql_parse (thd=0x7fff80015038, rawbuf=0x7fff80085890 "alter table t1 add partition (partition p4 history)", length=51, parser_state=0x7ffff7ea3650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8087
```
#### frame 1
```c++
2080      while (reorg_part < m_reorged_parts)
2081      {
2082        handler *file= m_reorged_file[reorg_part];
2083        uint32 new_part;
2084
....
2088        while (TRUE)
2089        {
2090          if ((result= file->ha_rnd_next(m_rec0)))
2091          {
2092            if (result != HA_ERR_END_OF_FILE)
2093              goto error;
2094            /*
2095              End-of-file reached, break out to continue with next partition or
2096              end the copy process.
2097            */
2098            break;
2099          }
2100          /* Found record to insert into new handler */
2101          if (m_part_info->get_partition_id(m_part_info, &new_part,
2102                                            &func_value))
2103          {
2104            /*
2105               This record is in the original table but will not be in the new
2106               table since it doesn't fit into any partition any longer due to
2107               changed partitioning ranges or list values.
2108            */
2109            (*deleted)++;
2110          }
2111          else
2112          {
2113            THD *thd= ha_thd();
2114            /* Copy record to new handler */
2115            (*copied)++;
2116            tmp_disable_binlog(thd); /* Do not replicate the low-level changes. */
2117            result= m_new_file[new_part]->ha_write_row(m_rec0);
2118            reenable_binlog(thd);
2119            if (result)
2120              goto error;
2121          }
```

**Comment by midenok** [comment]
## Bug 1: record is not moved into added partition
### Reproduce
```sql
create or replace table t1 (i int) with system versioning
partition by system_time interval 1 day starts '2021-01-01 12:00:00'
(partition p0 history, partition p1 history, partition p2 history, partition pn current);

alter table t1 add partition (partition p3 history, partition p4 history);

set timestamp= unix_timestamp('2021-01-10 00:00:00');
insert t1 values (5); delete from t1;
set timestamp= unix_timestamp('2021-01-06 00:00:00');
insert t1 values (6); delete from t1;

alter table t1 add partition (partition p5 history);
alter table t1 add partition (partition p6 history);
alter table t1 add partition (partition p7 history);
alter table t1 add partition (partition p8 history);
```
### Result
```
MariaDB [test]> select *, row_end from t1 partition (p4);
+------+----------------------------+
| i    | row_end                    |
+------+----------------------------+
|    5 | 2021-01-10 00:00:00.000000 |
|    6 | 2021-01-06 00:00:00.000000 |
+------+----------------------------+
```
### Expected
Row **5** goes to **p8**.
### Good
```sql
create or replace table t1 (i int) with system versioning
partition by system_time interval 1 day starts '2021-01-01 12:00:00'
(partition p0 history, partition p1 history, partition p2 history, partition pn current);

alter table t1 add partition (partition p3 history, partition p4 history);

set timestamp= unix_timestamp('2021-01-10 00:00:00');
insert t1 values (5); delete from t1;

alter table t1 add partition (partition p5 history);
```
Without record **6** record **5** goes to **p8**.

**Comment by midenok** [comment]
### Bad
```c++
#0  ha_partition::copy_partitions (this=0x7fff8015f730, copied=0x7ffff7e9d580, deleted=0x7ffff7e9d588) at /home/midenok/src/mariadb/trunk/src/sql/ha_partition.cc:2080
#1  0x00000000013fc550 in ha_partition::change_partitions (this=0x7fff8015f730, create_info=0x7ffff7ea0208, path=0x7ffff7e9d060 "./test/t1", copied=0x7ffff7e9d580, deleted=0x7ffff7e9d588, pack_frm_data=0x0, pack_frm_len=0) at /home/midenok/src/mariadb/trunk/src/sql/ha_partition.cc:2029
#2  0x0000000000b40bc9 in handler::ha_change_partitions (this=0x7fff8015f730, create_info=0x7ffff7ea0208, path=0x7ffff7e9d060 "./test/t1", copied=0x7ffff7e9d580, deleted=0x7ffff7e9d588, pack_frm_data=0x0, pack_frm_len=0) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:4651
#3  0x0000000000d4a01b in mysql_change_partitions (lpt=0x7ffff7e9d578) at /home/midenok/src/mariadb/trunk/src/sql/sql_partition.cc:5996
#4  0x0000000000d4938d in fast_alter_partition_table (thd=0x7fff80015038, table=0x7fff8015eb68, alter_info=0x7ffff7ea0138, create_info=0x7ffff7ea0208, table_list=0x7fff800859a8, db=0x7ffff7e9ee88, table_name=0x7ffff7e9ee98) at /home/midenok/src/mariadb/trunk/src/sql/sql_partition.cc:7361
#5  0x00000000008dd9bd in mysql_alter_table (thd=0x7fff80015038, new_db=0x7fff80019778, new_name=0x7fff80019b48, create_info=0x7ffff7ea0208, table_list=0x7fff800859a8, alter_info=0x7ffff7ea0138, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9551
#6  0x0000000000985dff in Sql_cmd_alter_table::execute (this=0x7fff80086428, thd=0x7fff80015038) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:491
#7  0x00000000007e6633 in mysql_execute_command (thd=0x7fff80015038) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6288
#8  0x00000000007d839f in mysql_parse (thd=0x7fff80015038, rawbuf=0x7fff80085890 "alter table t1 add partition (partition p5 history)", length=51, parser_state=0x7ffff7ea3650, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8087
```
```
(gdb) p m_reorged_parts
$5 = 0
```
### Good
```
(gdb) p m_reorged_parts
$5 = 1
```

**Comment by midenok** [comment]
## Good
### 1. `part_state` set to `PART_CHANGED`
```c++
#0  prep_alter_part_table (thd=0x7fff7c000cf8, table=0x7fff7c0c45a8, alter_info=0x7ffff41eb0d8, create_info=0x7ffff41eb1a8, alter_ctx=0x7ffff41e9e28, partition_changed=0x7ffff41e9ab6, fast_alter_table=0x7ffff41e9ab5) at /home/midenok/src/mariadb/trunk/src/sql/sql_partition.cc:5322
#1  0x00000000008ad471 in mysql_alter_table (thd=0x7fff7c000cf8, new_db=0x7fff7c005438, new_name=0x7fff7c005808, create_info=0x7ffff41eb1a8, table_list=0x7fff7c015178, alter_info=0x7ffff41eb0d8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9488
#2  0x000000000095552f in Sql_cmd_alter_table::execute (this=0x7fff7c015bf8, thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:491
#3  0x00000000007b7a08 in mysql_execute_command (thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6288
#4  0x00000000007a9710 in mysql_parse (thd=0x7fff7c000cf8, rawbuf=0x7fff7c015060 "alter table t1 add partition (partition p5 history)", length=51, parser_state=0x7ffff41ee640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8087
```
```c++
5318              if (*fast_alter_table && tab_part_info->vers_info->interval.is_set())
5319              {
5320                partition_element *hist_part= tab_part_info->vers_info->hist_part;
5321                if (hist_part->range_value <= thd->query_start())
5322                  hist_part->part_state= PART_CHANGED;
5323              }
```
```
(gdb) p hist_part->partition_name
$39 = 0x7fff7c0d2530 "p4"
```
```
(gdb) p hist_part->range_value
$45 = 1609923600  [January 6, 2021 12:00:00 PM]
(gdb) p thd->query_start()
$46 = 1610226000 [January 10, 2021 12:00:00 AM]
```
#### Bad
Condition 5321 is not passed:
```
(gdb) p hist_part->range_value
$43 = 1609923600 [January 6, 2021 12:00:00 PM]
(gdb) p thd->query_start()
$44 = 1609880400 [January 6, 2021 12:00:00 AM]
```
### 2. `m_reorged_parts` increased
```c++
#0  ha_partition::change_partitions (this=0x7fff7c0c4960, create_info=0x7ffff41eb1a8, path=0x7ffff41e8010 "./test/t1", copied=0x7ffff41e8528, deleted=0x7ffff41e8530, pack_frm_data=0x0, pack_frm_len=0) at /home/midenok/src/mariadb/trunk/src/sql/ha_partition.cc:1766
#1  0x0000000000b0edb2 in handler::ha_change_partitions (this=0x7fff7c0c4960, create_info=0x7ffff41eb1a8, path=0x7ffff41e8010 "./test/t1", copied=0x7ffff41e8528, deleted=0x7ffff41e8530, pack_frm_data=0x0, pack_frm_len=0) at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:4651
#2  0x0000000000d1590b in mysql_change_partitions (lpt=0x7ffff41e8520) at /home/midenok/src/mariadb/trunk/src/sql/sql_partition.cc:5996
#3  0x0000000000d14c96 in fast_alter_partition_table (thd=0x7fff7c000cf8, table=0x7fff7c0c3d98, alter_info=0x7ffff41eb0d8, create_info=0x7ffff41eb1a8, table_list=0x7fff7c015178, db=0x7ffff41e9e38, table_name=0x7ffff41e9e48) at /home/midenok/src/mariadb/trunk/src/sql/sql_partition.cc:7361
#4  0x00000000008ad786 in mysql_alter_table (thd=0x7fff7c000cf8, new_db=0x7fff7c005438, new_name=0x7fff7c005808, create_info=0x7ffff41eb1a8, table_list=0x7fff7c015178, alter_info=0x7ffff41eb0d8, order_num=0, order=0x0, ignore=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_table.cc:9551
#5  0x000000000095552f in Sql_cmd_alter_table::execute (this=0x7fff7c015bf8, thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/trunk/src/sql/sql_alter.cc:491
#6  0x00000000007b7a08 in mysql_execute_command (thd=0x7fff7c000cf8) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:6288
#7  0x00000000007a9710 in mysql_parse (thd=0x7fff7c000cf8, rawbuf=0x7fff7c015060 "alter table t1 add partition (partition p5 history)", length=51, parser_state=0x7ffff41ee640, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:8087
```
```c++
1758        do
1759        {
1760          partition_element *part_elem= part_it++;
1761          if (part_elem->part_state == PART_CHANGED ||
1762              part_elem->part_state == PART_REORGED_DROPPED)
1763          {
1764            m_reorged_parts+= num_subparts;
1765          }
1766        } while (++i < num_parts);
```
```
(gdb) p part_elem->partition_name
$37 = 0x7fff7c0cb390 "p4"
(gdb) p part_elem->part_state
$38 = PART_CHANGED
```
### Cause
`part_state` depends on `thd->query_start()`.

**Comment by midenok** [comment]
### Info: `range_value` updated
```c++
/* Set partition boundaries when rotating by INTERVAL */
static bool check_vers_constants(THD *thd, partition_info *part_info)
{
  uint hist_parts= part_info->num_parts - 1;
  Vers_part_info *vers_info= part_info->vers_info;
  vers_info->hist_part= part_info->partitions.head();
  vers_info->now_part= part_info->partitions.elem(hist_parts);

  if (!vers_info->interval.is_set())
    return 0;

  part_info->range_int_array=
    (longlong*) thd->alloc(hist_parts * sizeof(longlong));

  MYSQL_TIME ltime;
  List_iterator<partition_element> it(part_info->partitions);
  partition_element *el;
  my_tz_OFFSET0->gmt_sec_to_TIME(&ltime, vers_info->interval.start);
  while ((el= it++)->id < hist_parts)
  {
    if (date_add_interval(thd, &ltime, vers_info->interval.type,
                          vers_info->interval.step))
      goto err;
    uint error= 0;
    part_info->range_int_array[el->id]= el->range_value=
      my_tz_OFFSET0->TIME_to_gmt_sec(&ltime, &error);
    if (error)
      goto err;
    if (vers_info->hist_part->range_value <= thd->query_start())
      vers_info->hist_part= el;
  }
  return 0;
err:
  my_error(ER_DATA_OUT_OF_RANGE, MYF(0), "TIMESTAMP", "INTERVAL");
  return 1;
}
```
