### ISSUE TITLE
MDEV-16546 System versioning setting to allow history modification

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#592]
### TODO
- [x] Security fixes
- [x] Rebase on trunk
- [x] Implement DELETE
- [x] Implement Multi-DELETE
- [x] Test with implicit fields
- [x] Disable for non-conventional area (PS, SP)

### Review info
On Fri, May 3, 2019 at 8:43 PM Sergei Golubchik <serg@mariadb.com> wrote:
>
> Hi, Aleksey!
>
> On May 03, Aleksey Midenkov wrote:
> > revision-id: ef2519fee4e (versioning-1.0.5-17-gef2519fee4e)
> > parent(s): 56145be2951
> > author: Aleksey Midenkov <midenok@gmail.com>
> > committer: Aleksey Midenkov <midenok@gmail.com>
> > timestamp: 2018-06-28 13:42:09 +0300
> > message:
> >
> > MDEV-16546 System versioning setting to allow history modification
> >
> > 1. Add server variable system_versioning_modify_history which will
> > allow to set values for row_start, row_end in DML operations.
> >
> > 2. If secure_timestamp is YES or REPLICATION,
> > system_versioning_modify_history does not have effect. If
> > secure_timestamp is SUPER, system_versioning_modify_history requires
> > special privilege (same as for setting current timestamp).
>
> I thought more about this idea. We don't really want to have the history
> editable, do we? But it's needed for replication, to keep the master and
> slave identical. That's what secure_timestamp is for.
>
> The idea was that this new variable, system_versioning_modify_history,
> will be just a convenience feature, it will not allow history editing
> any more than one can do without it.
>
> But now I suspect that even with secure_timestamp=NO one cannot truly
> edit history. One can only insert new rows with arbitrary timestamps.
> For example, to insert a row with row_start=1000 and row_end=2000, one
> needs to do (if secure_timestamp=NO):
>
>   set timestamp=1000;
>   insert row;
>   set timestamp=2000;
>   delete row;
>
> But I don't see how one can update or delete a history row with
> secure_timestamp=NO.
>
> Now, with a SUPER privilege and secure_timestamp=NO or SUPER, one can
> use the BINLOG command and truly edit the history arbitrarily, by faking
> row events.
>
> The conclusion, I believe, is that system_versioning_modify_history
> should allow INSERTs when secure_timestamp=NO, and it should allow
> UPDATE/DELETE only for a SUPER user when secure_timestamp=NO or SUPER.
>
> The second thing I don't like at all, is when a table is created like
>
>   CREATE TABLE t1 (a int) WITH SYSTEM VERSIONING
>
> with row_start/row_end implicit. You don't have it in the test, but
> anyway one should be able to load history into such a table, while the
> table does not have row_start and row_end columns. From the user point
> of view these columns don't exist, they're pseudo-columns, like ROWID.
> They just cannot be insertable-into, conceptually. But a user will want
> to restore the history, right? I don't have a solution for this yet :(
> Any ideas?
>
> See below a couple of minor comments about the patch itself.
>
<details> 
  <summary>More ...</summary>
<pre>
> > diff --git a/sql/sql_class.cc b/sql/sql_class.cc
> > index 718d2424463..ee0290951d9 100644
> > --- a/sql/sql_class.cc
> > +++ b/sql/sql_class.cc
> > @@ -732,9 +732,8 @@ THD::THD(my_thread_id id, bool is_wsrep_applier, bool skip_global_sys_var_lock)
> >     m_stmt_da(&main_da),
> >     tdc_hash_pins(0),
> >     xid_hash_pins(0),
> > -   m_tmp_tables_locked(false)
> > +   m_tmp_tables_locked(false),
> >  #ifdef WITH_WSREP
> > -  ,
> >     wsrep_applier(is_wsrep_applier),
> >     wsrep_applier_closing(false),
> >     wsrep_client_thread(false),
> > @@ -742,8 +741,9 @@ THD::THD(my_thread_id id, bool is_wsrep_applier, bool skip_global_sys_var_lock)
> >     wsrep_po_handle(WSREP_PO_INITIALIZER),
> >     wsrep_po_cnt(0),
> >     wsrep_apply_format(0),
> > -   wsrep_ignore_table(false)
> > +   wsrep_ignore_table(false),
> >  #endif
> > +   modify_history_warned(false)
>
> keep wsrep additions at the end, please,
> add modify_history_warned before them
>
> >  {
> >    ulong tmp;
> >    bzero(&variables, sizeof(variables));
> > @@ -3874,6 +3874,7 @@ void THD::end_statement()
> >    lex_end(lex);
> >    delete lex->result;
> >    lex->result= 0;
> > +  modify_history_warned= false;
> >    /* Note that free_list is freed in cleanup_after_query() */
> > 
> >    /*
> > @@ -7122,6 +7123,35 @@ static bool protect_against_unsafe_warning_flood(int unsafe_type)
> >    DBUG_RETURN(unsafe_warning_suppression_active[unsafe_type]);
> >  }
> > 
> > +bool THD::vers_modify_history()
> > +{
> > +  if (!variables.vers_modify_history)
> > +    return false;
> > +  enum_sql_command c= lex->sql_command;
> > +  if (c != SQLCOM_UPDATE && c != SQLCOM_INSERT && c != SQLCOM_INSERT_SELECT &&
> > +      c != SQLCOM_UPDATE_MULTI && c != SQLCOM_REPLACE)
>
> why not delete? see above, if one can do it with a hand-crafted BINLOG
> statement, there's no reason to disable a more convenient way of doing
> the same.
>
> > +    return false;
> > +  if (opt_secure_timestamp >= SECTIME_REPL)
> > +  {
> > +    if (!modify_history_warned)
> > +    {
> > +      push_warning_printf(this, Sql_condition::WARN_LEVEL_WARN,
> > +                          WARN_VERS_MODIFY_HISTORY,
> > +                          ER_THD(this, WARN_VERS_MODIFY_HISTORY));
> > +      modify_history_warned= true;
> > +    }
> > +    return false;
> > +  }
>
> I don't think you need any special handling here. Just the regular
> ER_WARNING_NON_DEFAULT_VALUE_FOR_GENERATED_COLUMN is enough.
>
> > +  if (opt_secure_timestamp == SECTIME_SUPER &&
> > +      !(security_ctx->master_access & SUPER_ACL))
> > +  {
> > +    my_error(ER_SPECIFIC_ACCESS_DENIED_ERROR, MYF(0), "SUPER");
> > +    return false;
> > +  }
> > +  return true;
> > +
> > +}
> > +
> >  MYSQL_TIME THD::query_start_TIME()
> >  {
> >    MYSQL_TIME res;
> > diff --git a/sql/sql_insert.cc b/sql/sql_insert.cc
> > index a60a6f2975e..cf7db3e8ec3 100644
> > --- a/sql/sql_insert.cc
> > +++ b/sql/sql_insert.cc
> > @@ -1634,6 +1634,9 @@ static int last_uniq_key(TABLE *table,uint keynr)
> >  int vers_insert_history_row(TABLE *table)
> >  {
> >    DBUG_ASSERT(table->versioned(VERS_TIMESTAMP));
> > +  if (!table->vers_write)
> > +    return 0;
>
> wouldn't it be better to do it in the caller? with
>
>   DBUG_ASSERT(table->vers_write);
>
> here? Your typical calling sequence is
>
>      store_record(table, record[2]);
>      error= vers_insert_history_row(table);
>      restore_record(table, record[2]);
>
> there'd be useless store_record()/restore_record() if
> vers_insert_history_row() will do nothing.
>
> > +
> >    restore_record(table,record[1]);
>
> Regards,
> Sergei
> Chief Architect MariaDB
> and security@mariadb.org
</pre>
</details>
### Info
#292 #117

**Comment by midenok** [comment]
### mysqld_get_one_option()
```c++
#0  mysqld_get_one_option (optid=117, opt=0x25e2a38, argument=0x25d45cf "midenok") at /home/midenok/src/mariadb/10.3/src/sql/mysqld.cc:9097
#1  0x00000000013d3850 in handle_options (argc=0x1d265c0 <remaining_argc>, argv=0x1d265c8 <remaining_argv>, longopts=0x25e0888, get_one_option=0x6270c0 <mysqld_get_one_option(int, my_option const*, char*)>) at /home/midenok/src/mariadb/10.3/src/mysys/my_getopt.c:625
#2  0x000000000062e135 in get_options (argc_ptr=0x1d265c0 <remaining_argc>, argv_ptr=0x1d265c8 <remaining_argv>) at /home/midenok/src/mariadb/10.3/src/sql/mysqld.cc:9658
#3  0x00000000006214ca in init_common_variables () at /home/midenok/src/mariadb/10.3/src/sql/mysqld.cc:4362
#4  0x0000000000620198 in mysqld_main (argc=32, argv=0x25d4e38) at /home/midenok/src/mariadb/10.3/src/sql/mysqld.cc:5925
#5  0x000000000061bbe2 in main (argc=8, argv=0x7fffffffba58) at /home/midenok/src/mariadb/10.3/src/sql/main.cc:25
```
### `opt_secure_timestamp` assigned from command line
```c++
#0  0x00000000013d4528 in setval (opts=0x25eb558, value=0x1d1fea0 <opt_secure_timestamp>, argument=0x7fffffffbfd9 "yes", set_maximum_value=0 '\000') at /home/midenok/src/mariadb/10.3/src/mysys/my_getopt.c:802
#1  0x00000000013d3857 in handle_options (argc=0x1d265c0 <remaining_argc>, argv=0x1d265c8 <remaining_argv>, longopts=0x25e0888, get_one_option=0x6270c0 <mysqld_get_one_option(int, my_option const*, char*)>) at /home/midenok/src/mariadb/10.3/src/mysys/my_getopt.c:622
#2  0x000000000062e135 in get_options (argc_ptr=0x1d265c0 <remaining_argc>, argv_ptr=0x1d265c8 <remaining_argv>) at /home/midenok/src/mariadb/10.3/src/sql/mysqld.cc:9658
#3  0x00000000006214ca in init_common_variables () at /home/midenok/src/mariadb/10.3/src/sql/mysqld.cc:4362
#4  0x0000000000620198 in mysqld_main (argc=32, argv=0x25d4e38) at /home/midenok/src/mariadb/10.3/src/sql/mysqld.cc:5925
#5  0x000000000061bbe2 in main (argc=8, argv=0x7fffffffba58) at /home/midenok/src/mariadb/10.3/src/sql/main.cc:25
```

**Comment by midenok** [comment]
```
    MDEV-16546 System versioning setting to allow history modification
    
    Add server variable system_versioning_modify_history which will allow
    to modify history by DML operations.
    
    If secure_timestamp is YES or REPLICATION or execution is from
    prepared statement system_versioning_modify_history does not have
    effect. If secure_timestamp is SUPER, system_versioning_modify_history
    requires special privilege (same as for setting current timestamp).
    
    Setting system_versioning_modify_history to ON is disallowed if
    secure_timestamp is ON or REPLICATION. If secure_timestamp is SUPER,
    allow only for superuser. This is applicable to command-line as well.
    
    UPDATE, DELETE of historical rows is allowed only for superuser and
    only when row_start or row_end is specified explicitly in WHERE
    condition.
    
    Note that PS is disabled because permanent Item::transform() is not
    supported which is the subject for future refactoring if it will be
    needed.
    
    Depends on:
    
    MDEV-18727 improve DML operation of System Versioning
```
