### ISSUE TITLE
Configure nightly builds (Jenkins)

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#62]
### Jenkins box: [sunny.my.to](http://sunny.my.to:8080/)
- [x] Create simple job for building MariaDB and run full test suite;
- [x] Tests skipping;
- [ ] Setup schedule to run nightly: nightly builds must be separate jenkins *Item* (`mariadb-nightly` vs `mariadb-manual`);
- [x] Tell how many rejects available, forge scp command to copy test rejects from Jenkins box to localhost;
- [ ] Backup Jenkins config (see [Administering Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Administering+Jenkins));
- [ ] Parse tests output to generate JUnit report, probably with the help of xUnit (some info [here](http://stackoverflow.com/questions/14753550/simplest-plugin-to-parse-and-display-test-results-in-jenkins) and [here](http://stackoverflow.com/questions/4922867/junit-xml-format-specification-that-hudson-supports)). Parsing should recognize failure cause:

```
tokudb.bf_delete                         [ fail ]  timeout after 900 seconds
```
- [ ] JUnit report should contain each test run time;
- [ ] Setup status badge (Embeddable Build Status).

**Comment by midenok** [comment]
"Tell how many rejects available" is not reached when tests fail.

**Comment by midenok** [comment]
### Backup
#### Mount Googe Drive
```
google-drive-ocamlfuse /mnt/gdrive
```

#### Do backup
```
/var/lib/jenkins/bin/backup
```

### TODO
- [ ] Automount from `fstab`
- [ ] Backup by `cron`.

**Comment by midenok** [comment]
Fixed skipping tests (`skip_tests` parameter).

**Comment by midenok** [comment]
Please, make backup of current Jenkins config by the above instruction. Fix problems if something will not work.

**Comment by midenok** [comment]
This is minor priority.
